import assert from 'node:assert/strict';
import {build} from 'esbuild';
import path from 'node:path';
import {chromium} from 'playwright';
const fixture=await build({stdin:{contents:`import React from 'react';import{createRoot}from'react-dom/client';import{OpenVaultEditor}from'./src/local-vault/VaultApp';import{setVaultTransport,VaultError}from'./src/local-vault/bridge';import{emptyDocumentSnapshot}from'./src/lib/documents/model';const root=createRoot(document.getElementById('root'));window.calls=0;window.mode='transient';const doc=emptyDocumentSnapshot();doc.content.title='Saved note';doc.content.body='Saved writing';const file={path:'Notes/Test.textpack',hash:'h',markdown:'---\\ntextTextId: "11111111-1111-4111-8111-111111111111"\\n---\\nSaved writing',documentJSON:JSON.stringify(doc)};setVaultTransport(async method=>{if(method==='collaborationConfig'){window.calls++;if(window.mode==='terminal')throw new VaultError('Access unavailable','403');if(window.mode==='offline'||window.calls===1)throw new VaultError('Temporary connection','503');return null;}if(method==='write')throw new VaultError('Offline save','503');if(method==='list')return{root:'fixture',items:[],folders:[]};if(method==='read')return file;return null;});window.open=(key,draft=false)=>{if(draft)localStorage.setItem('texttext:vault-draft:fixture:Notes/Test.textpack',JSON.stringify({base:doc,document:{...doc,content:{...doc.content,body:'Recovered writing'}}}));root.render(<OpenVaultEditor key={key} initial={file} root='fixture' onChanged={()=>{}} onRemoved={()=>{}} registerFlush={()=>{}}/>)};`,resolveDir:process.cwd(),loader:'tsx'},plugins:[{name:'local-components',setup(b){for(const [name,file] of [['ParticipantsRow','LocalParticipants.tsx'],['WorkspaceTypeLibrary','LocalTemplateLibrary.tsx'],['CommandLayer','LocalKeyboard.ts']])b.onResolve({filter:new RegExp('(?:^|/)'+name+'$')},()=>({path:path.resolve('src/local-vault',file)}))}}],bundle:true,write:false,outdir:"/tmp/texttext-bootstrap-fixture",jsx:'automatic',loader:{'.css':'empty','.jpg':'dataurl','.png':'dataurl','.svg':'dataurl'},define:{'process.env.NODE_ENV':'"production"'}});
const browser=await chromium.launch();
try{
 const page=await browser.newPage();await page.route('**/*',route=>route.fulfill({contentType:'text/html',body:'<div id="root"></div>'}));await page.goto('https://fixture.test');await page.addScriptTag({content:fixture.outputFiles.find(file=>file.path.endsWith(".js")).text});
 await page.evaluate(()=>window.open('first'));await page.getByText('Saved writing',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.calls),3);
 await page.evaluate(()=>{window.mode='terminal';window.calls=0;window.open('terminal')});await page.getByText('Access unavailable',{exact:false}).waitFor();await page.waitForTimeout(1400);assert.equal(await page.evaluate(()=>window.calls),1);
 await page.evaluate(()=>{window.mode='offline';window.calls=0;window.open('offline')});await page.getByRole('button',{name:'Retry',exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.calls),3);
 await page.evaluate(()=>{window.mode='ready';window.dispatchEvent(new Event('online'))});await page.getByText('Saved writing',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.calls),5);
 await page.evaluate(()=>{window.mode='terminal';window.calls=0;window.open('draft',true)});await page.getByText('Recovered writing',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.calls),1);
 // A recoverable local draft remains editable when the promotion capability check is denied.
 await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>window.calls),1);
 assert.ok(await page.evaluate(()=>Object.values(localStorage).some(value=>value.includes('Recovered writing'))));
 console.log('PASS actual editor bootstrap: transient recovery, bounded exhaustion/online recovery, terminal refusal and draft preservation during promotion checks.');
}finally{await browser.close();}
