import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { chromium } from 'playwright';
import { readFile } from 'node:fs/promises';
const bundle=await build({stdin:{contents:`import React from'react';import{createRoot}from'react-dom/client';import{VaultDocumentGrid}from'./src/local-vault/VaultDocumentGrid';import{setVaultTransport}from'./src/local-vault/bridge';window.calls=[];window.opened=[];setVaultTransport(async(method,params)=>{window.calls.push(method);if(method==='preview')return{title:params.path.split('/').at(-1).replace('.textpack',''),excerpt:'A useful saved thought with enough text to preview the document.',image:params.path.startsWith('Blog/')?{data:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aD1sAAAAASUVORK5CYII=',contentType:'image/png'}:undefined};throw Error('Unexpected '+method)});const root=createRoot(document.getElementById('root'));const items=[{path:'Notes/Ideas.textpack'},{path:'Blog/On writing.textpack'},{path:'Projects/Research.textpack'}];window.renderLibrary=(workspace='A',folder='')=>root.render(<VaultDocumentGrid listing={{root:workspace,name:workspace,items}} folder={folder} busy={false} onOpen={path=>window.opened.push(path)}/>);window.renderLibrary();`,resolveDir:process.cwd(),loader:'tsx'},bundle:true,write:false,outdir:'/tmp/texttext-layout-fixture',jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'}});
const browser=await chromium.launch();
try{
 const page=await browser.newPage({viewport:{width:1100,height:720}});await page.route('https://layout.test/**',route=>route.fulfill({contentType:'text/html',body:'<div class="vault-app" id="root"></div>'}));
 const mount=async()=>{await page.addStyleTag({content:await readFile('src/local-vault/style.css','utf8')});for(const file of bundle.outputFiles.filter(f=>f.path.endsWith('.css')))await page.addStyleTag({content:file.text});await page.addStyleTag({content:'.vault-app{display:block;padding:24px;min-height:100vh;height:auto;}'});await page.addScriptTag({content:bundle.outputFiles.find(f=>f.path.endsWith('.js')).text});await page.getByRole('group',{name:'Document view'}).waitFor()};
 await page.goto('https://layout.test/');await mount();
 const titles=()=>page.locator('.vault-document-grid strong,.vault-document-list strong').allTextContents();
 const expected=['On writing','Ideas','Research'];assert.deepEqual(await titles(),expected);
 assert.equal(await page.getByRole('button',{name:'Cards',exact:true}).getAttribute('aria-pressed'),'true');
 await page.getByRole('button',{name:'List',exact:true}).click();assert.deepEqual(await titles(),expected);assert.equal(await page.locator('.vault-document-list > button').count(),3);assert.equal(await page.locator('.vault-document-list').getAttribute('data-layout'),'list');await page.locator('.vault-document-list img').waitFor();assert.equal(await page.locator('.vault-document-list .vault-file-excerpt').count(),3);
 await page.locator('.vault-document-list > button').first().click();assert.deepEqual(await page.evaluate(()=>window.opened),['Blog/On writing.textpack']);
 for(const theme of ['light','dark']){await page.emulateMedia({colorScheme:theme});for(const view of ['List','Cards']){await page.getByRole('button',{name:view,exact:true}).click();await page.screenshot({path:'/tmp/texttext-document-'+view.toLowerCase()+'-'+theme+'.png'});}}
 await page.getByRole('button',{name:'List',exact:true}).click();await page.reload();await mount();assert.equal(await page.getByRole('button',{name:'List',exact:true}).getAttribute('aria-pressed'),'true');assert.deepEqual(await titles(),expected);
 await page.evaluate(()=>window.renderLibrary('B'));await page.waitForFunction(()=>document.querySelector('.vault-document-grid'));assert.equal(await page.getByRole('button',{name:'Cards',exact:true}).getAttribute('aria-pressed'),'true');
 await page.evaluate(()=>window.renderLibrary('A'));await page.waitForFunction(()=>document.querySelector('.vault-document-list'));
 await page.setViewportSize({width:390,height:700});await page.screenshot({path:'/tmp/texttext-document-list-narrow.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.evaluate(()=>window.renderLibrary('A','Notes'));await page.getByRole('group',{name:'Document view'}).waitFor({state:'detached'});
 assert((await page.evaluate(()=>window.calls)).every(method=>method==='preview'));console.log('PASS library layout: identical items/open action, List/Cards, saved reload, workspace isolation, specialized Notes unchanged, no content writes, light/dark/narrow.');
}finally{await browser.close()}
