import assert from 'node:assert/strict';import{mkdtemp,writeFile,readFile,rm,symlink}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';import{chromium}from'playwright';import{buildLocalVault}from'../../../scripts/build-local-vault.mjs';
const dir=await mkdtemp(path.join(tmpdir(),'texttext-capabilities-'));let browser;
try{
const root=process.cwd();await symlink(path.join(root,'node_modules'),path.join(dir,'node_modules'));
await writeFile(path.join(dir,'entry.tsx'),`
import React from '${root}/node_modules/react/index.js';import{createRoot}from'${root}/node_modules/react-dom/client.js';import{VaultApp}from'${root}/src/local-vault/VaultApp';import{setVaultTransport}from'${root}/src/local-vault/bridge';import{emptyDocumentSnapshot}from'${root}/src/lib/documents/model';import '${root}/src/local-vault/style.css';
let doc=emptyDocumentSnapshot();doc.content.title='Shared note';doc.content.body='Keep this content.';let file={path:'Notes/Shared.textpack',hash:'a',markdown:'---\\ntextTextId: 11111111-1111-4111-8111-111111111111\\n---\\nKeep this content.',documentJSON:JSON.stringify(doc)};
window.editable=false;window.calls=[];
setVaultTransport(async(method,params)=>{window.calls.push(method);if(method==='list')return{root:'/shared',folders:['Notes'],items:[{path:file.path,itemId:'11111111-1111-4111-8111-111111111111',canEditContent:window.editable}],fullAccess:false,canCreateContent:false,writableFolders:window.editable?['Notes']:[]};if(method==='folderViews')return{files:[]};if(method==='connection')return{connected:true,available:true,root:'/shared'};if(method==='collaborationConfig')return null;if(method==='read')return file;if(method==='preview')return{title:'Shared note',cardBody:'Keep this content.',document:doc};if(method==='templates')return{files:[]};throw Error(method);});
const app=createRoot(document.getElementById('root'));app.render(<VaultApp/>);
`);
await buildLocalVault({entry:path.join(dir,'entry.tsx'),output:dir});browser=await chromium.launch();const page=await browser.newPage();await page.route('https://capabilities.test/**',r=>r.fulfill({contentType:'text/html',body:'<div id="root"></div>'}));await page.goto('https://capabilities.test');await page.addStyleTag({content:await readFile(path.join(dir,'app.css'),'utf8')});await page.addScriptTag({content:await readFile(path.join(dir,'app.js'),'utf8')});
await page.waitForFunction(()=>window.calls.includes('list'));await page.locator('summary').filter({hasText:'Notes'}).first().click();assert.equal(await page.getByRole('button',{name:'New note',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Edit Shared note',exact:true}).count(),0);
await page.evaluate(()=>window.dispatchEvent(new CustomEvent('texttext:vault-open',{detail:{path:'Notes/Shared.textpack'}})));await page.getByText('Read only',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:/Edit card|Edit this|Edit story/}).count(),0);assert.equal(await page.locator('[contenteditable="true"]').count(),0);await page.evaluate(()=>window.dispatchEvent(new Event('texttext:vault-edit-item')));assert.equal(await page.locator('[contenteditable="true"]').count(),0);
await page.getByText('More',{exact:true}).click();assert.equal(await page.getByRole('button',{name:'Delete',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Rename or move',exact:true}).count(),0);await page.keyboard.press('Escape');
await page.evaluate(()=>{window.editable=true;window.dispatchEvent(new Event('texttext:vault-changed'));});await page.getByText('Read only',{exact:true}).waitFor({state:'hidden'});await page.getByRole('button',{name:'Edit story',exact:true}).waitFor();assert.equal(await page.getByText('Read only',{exact:true}).count(),0);await page.getByText('More',{exact:true}).click();assert.equal(await page.getByRole('button',{name:'Delete',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Rename or move',exact:true}).count(),0);assert.equal(await page.evaluate(()=>window.calls.includes('write')||window.calls.includes('delete')),false);
console.log('PASS shared capabilities: native scoped reader has no edit/create/move/delete, refreshed editor grant enables edit without granting destructive actions.');
}finally{await browser?.close();await rm(dir,{recursive:true,force:true});}
