import assert from 'node:assert/strict';
import {mkdtemp, writeFile, readFile, rm, symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {chromium} from 'playwright';
import {buildLocalVault} from '../../../scripts/build-local-vault.mjs';

const dir = await mkdtemp(path.join(tmpdir(), 'texttext-parent-picker-'));
let browser;
try {
  const root = process.cwd();
  await symlink(path.join(root, 'node_modules'), path.join(dir, 'node_modules'));
  await writeFile(path.join(dir, 'entry.tsx'), `
import React,{useState} from '${root}/node_modules/react/index.js';
import {createRoot} from '${root}/node_modules/react-dom/client.js';
import {FieldInput} from '${root}/src/components/document/FieldInput';
const choices=[{id:'one',label:'Research'},{id:'two',label:'Publishing'}];
const remote={search:async()=>choices,resolve:async(id)=>{if(id==='two'&&window.delaySelection){window.delaySelection=false;return new Promise(resolve=>window.finishSelection=()=>resolve(choices[1]));}return choices.find(c=>c.id===id)??{id,label:id};}};
function Test(){const [parents,setParents]=useState(['missing']);const [useRemote,setRemote]=useState(false);const [multiple,setMultiple]=useState(true);window.parents=parents;window.remoteEnabled=useRemote;window.setParents=setParents;window.setRemote=setRemote;window.setMultiple=setMultiple;
return <FieldInput field={{id:'parents',label:'Parents',type:'reference',target:'document',multiple,required:false,visibility:'public'}} value={parents} documentReferences={useRemote?remote:undefined} referenceChoices={choices} onChange={setParents} onOpenReference={id=>window.opened=id}/>;}
createRoot(document.getElementById('root')).render(<Test/>);
`);
  await buildLocalVault({entry:path.join(dir,'entry.tsx'),output:dir});
  browser = await chromium.launch();
  const page = await browser.newPage();
  const errors=[]; page.on('pageerror', error=>errors.push(error.message));
  await page.route('https://parent.test/**', route=>route.fulfill({contentType:'text/html',body:'<div id="root"></div>'}));
  await page.goto('https://parent.test/');
  await page.addScriptTag({content:await readFile(path.join(dir,'app.js'),'utf8')});
  await page.getByText('Unavailable item',{exact:true}).waitFor();
  await page.getByText('Add parent',{exact:true}).click();
  await page.getByRole('searchbox',{name:'Find item'}).fill('Res');
  await page.getByRole('button',{name:'Research',exact:true}).click();
  assert.deepEqual(await page.evaluate(()=>window.parents),['missing','one']);
  assert.equal(await page.locator('details[open]').count(),0);
  await page.getByRole('button',{name:'Research',exact:true}).click();
  assert.equal(await page.evaluate(()=>window.opened),'one');
  await page.getByText('Add parent',{exact:true}).click();
  await page.getByRole('searchbox',{name:'Find item'}).press('Escape');
  assert.equal(await page.locator('summary').evaluate(el=>el===document.activeElement),true);
  await page.getByRole('button',{name:'Remove Research',exact:true}).click();
  assert.deepEqual(await page.evaluate(()=>window.parents),['missing']);
  await page.evaluate(()=>{window.setRemote(true);window.delaySelection=true;});
  await page.getByText('Add parent',{exact:true}).click();
  await page.getByRole('searchbox',{name:'Find item'}).fill('Publishing');
  await page.getByRole('button',{name:'Publishing',exact:true}).click();
  await page.waitForFunction(()=>typeof window.finishSelection==='function');
  await page.evaluate(()=>window.setParents(['concurrent']));
  await page.getByText('concurrent',{exact:true}).waitFor();
  await page.evaluate(()=>window.finishSelection());
  await page.waitForFunction(()=>window.parents.includes('two'));
  assert.deepEqual(await page.evaluate(()=>window.parents),['concurrent','two']);
  await page.getByRole('button',{name:'Remove Publishing',exact:true}).click();
  await page.evaluate(()=>{window.delaySelection=true;window.finishSelection=null;});
  await page.getByText('Add parent',{exact:true}).click();
  await page.getByRole('searchbox',{name:'Find item'}).fill('Publishing');
  await page.getByRole('button',{name:'Publishing',exact:true}).click();
  await page.waitForFunction(()=>typeof window.finishSelection==='function');
  await page.evaluate(()=>window.setRemote(false));
  await page.waitForFunction(()=>window.remoteEnabled===false);
  await page.getByRole('button',{name:'Publishing',exact:true}).waitFor();
  await page.evaluate(()=>window.finishSelection());
  await page.getByRole('button',{name:'Publishing',exact:true}).waitFor({state:'visible'});
  assert.deepEqual(await page.evaluate(()=>window.parents),['concurrent']);
  await page.evaluate(()=>{window.setRemote(true);window.setMultiple(false);window.setParents([]);window.delaySelection=true;window.finishSelection=null;});
  await page.waitForFunction(()=>window.remoteEnabled===true&&window.parents.length===0);
  await page.getByRole('button',{name:'Publishing',exact:true}).click();
  await page.waitForFunction(()=>typeof window.finishSelection==='function');
  await page.evaluate(()=>window.setParents(['one']));
  await page.getByRole('button',{name:'Research',exact:true}).waitFor();
  await page.evaluate(()=>window.finishSelection());
  await page.getByRole('alert').filter({hasText:'This selection changed'}).waitFor();
  assert.deepEqual(await page.evaluate(()=>window.parents),['one']);
  assert.deepEqual(errors,[]);
  console.log('PASS parent picker: stable IDs, navigation, removal, Escape, concurrent changes preserved and stale source selection ignored.');
} finally {await browser?.close();await rm(dir,{recursive:true,force:true});}
