import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {build} from 'esbuild';
import {chromium} from 'playwright';
const root=process.cwd();const mocks={
 'collaboration-client':`import * as Y from 'yjs';export class FileCollaborationClient{doc=new Y.Doc();hasBaseline=true;canEdit=true;hasPendingChanges=false;status='ready';constructor(o){this.o=o;window.client=this;}async start(){this.o.onStatus('ready');}setActive(){}async flushLocal(){return true}destroy(){this.doc.destroy()}}`,
 'presence-client':`export class FilePresenceClient{constructor(o){window.presence=o}setActive(){}destroy(){}}`
};
const result=await build({stdin:{contents:`import React from 'react';import{createRoot}from'react-dom/client';import{CollaborativeVaultEditor}from'./src/local-vault/CollaborativeVaultEditor';import{emptyDocumentSnapshot}from'./src/lib/documents/model';import{setVaultTransport}from'./src/local-vault/bridge';import{writePayload}from'./src/local-vault/model';window.parses=0;const doc=emptyDocumentSnapshot({id:'texttext.note',version:1});doc.content.title='Reader';doc.content.body='**Original** body';window.doc=doc;const file=writePayload({path:'Notes/Test.textpack',hash:'h',markdown:'---\\ntextTextId: "11111111-1111-4111-8111-111111111111"\\n---\\n\\n'},doc);setVaultTransport(async()=>null);createRoot(document.getElementById('root')).render(<CollaborativeVaultEditor initial={file} root='fixture' config={{namespace:'fixture',workspaceId:'fixture',itemId:'11111111-1111-4111-8111-111111111111'}} registerFlush={()=>{}} onChanged={()=>{}} onRemoved={()=>{}}/>);`,resolveDir:root,loader:'tsx'},bundle:true,write:false,outdir:"/tmp/texttext-reader-fixture",jsx:'automatic',minify:true,define:{'process.env.NODE_ENV':'"production"'},loader:{'.css':'empty','.jpg':'dataurl','.png':'dataurl','.svg':'dataurl'},plugins:[{name:'fixture',setup(b){
 b.onResolve({filter:/^\.\/(collaboration-client|presence-client)$/},args=>({path:args.path.slice(2),namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},args=>({contents:mocks[args.path],resolveDir:root,loader:'ts'}));
 b.onLoad({filter:/DocumentRenderer\.tsx$/},async args=>({contents:(await readFile(args.path,'utf8')).replace('  return (\n    <ReactMarkdown','  window.parses++;\n  return (\n    <ReactMarkdown'),loader:'tsx'}));
 for(const [name,file] of [['ParticipantsRow','LocalParticipants.tsx'],['WorkspaceTypeLibrary','LocalTemplateLibrary.tsx'],['CommandLayer','LocalKeyboard.ts']])b.onResolve({filter:new RegExp('(?:^|/)'+name+'$')},()=>({path:path.resolve('src/local-vault',file)}));
}}]});let browser;
try{browser=await chromium.launch();const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://reader.test/**',route=>route.fulfill({contentType:'text/html',body:'<div id="root"></div>'}));await page.goto('https://reader.test/');await page.addScriptTag({content:result.outputFiles[0].text});await page.getByText('Original',{exact:true}).waitFor().catch(async error=>{throw new Error(JSON.stringify({errors,body:await page.locator('body').innerText()}),{cause:error})});const initial=await page.evaluate(()=>window.parses);
 for(let i=0;i<4;i++){await page.evaluate(i=>window.client.o.onStatus('ready','Status '+i),i);await page.getByText('Status '+i,{exact:true}).waitFor();}
 const afterStatus=await page.evaluate(()=>window.parses);await page.evaluate(()=>window.presence.onPresence([{clientId:'peer',userName:'Test peer',color:'#123456'}]));await page.getByText('Test peer',{exact:true}).waitFor();const afterPresence=await page.evaluate(()=>window.parses);console.log(JSON.stringify({initial,afterStatus,afterPresence}));
 if(!process.argv.includes('--baseline')){assert.equal(afterStatus,initial);assert.equal(afterPresence,initial);}
 await page.evaluate(()=>{window.doc={...window.doc,content:{...window.doc.content,body:'**Changed** body'}};window.client.o.onChange(window.doc)});await page.getByText('Changed',{exact:true}).waitFor();assert.ok(await page.evaluate(()=>window.parses)>initial);
 await page.evaluate(()=>{window.doc={...window.doc,content:{...window.doc.content,body:'**Changed** body\n\n![Picture](assets/p.png)',assets:[{id:'p',kind:'image',src:'assets/p.png',alt:'First picture',width:10,height:20}]}};window.client.o.onChange(window.doc,{assets:[{filename:'p.png',data:'eA==',contentType:'image/png'}]})});
 const image=page.locator('.vault-note-display img');await image.waitFor({state:"attached",timeout:5000});const originalURL=await image.getAttribute('src');assert.ok(originalURL.startsWith('blob:'));assert.equal(await image.getAttribute('alt'),'First picture');
 await page.evaluate(()=>{window.doc={...window.doc,content:{...window.doc.content,assets:[{...window.doc.content.assets[0],alt:'Updated picture',width:30,height:40}]}};window.client.o.onChange(window.doc,{assets:[{filename:'p.png',data:'eQ==',contentType:'image/png'}]})});await page.waitForFunction(()=>document.querySelector('.vault-note-display img')?.alt==='Updated picture');assert.notEqual(await image.getAttribute('src'),originalURL);assert.equal(await image.getAttribute('width'),'30');
 await page.evaluate(()=>{window.doc={...window.doc,presentation:{...window.doc.presentation,theme:{...window.doc.presentation.theme,typography:'mono'},template:{id:'texttext.article',version:1}}};window.client.o.onChange(window.doc)});await page.locator('.vault-story-display').waitFor();assert.equal(await page.locator('.tt-document').getAttribute('data-typography'),'mono');
 assert.deepEqual(errors,[]);
}finally{await browser?.close();}
