// Generated by scripts/generate-builtin-presets.ts from presets/builtin/*.textpack.
// This facade pairs definitions and previews only in consumers that need both.
import type { DocumentSnapshot } from "@/lib/documents/model";
import type { TemplateDefinition } from "@/lib/presentation/schema";
import { GENERATED_BUILTIN_EXAMPLES } from "./generated-builtin-examples";
import { GENERATED_BUILTIN_TEMPLATES } from "./generated-builtin-templates";

export type GeneratedBuiltinPreset = {
  template: TemplateDefinition;
  document: DocumentSnapshot;
};

export const GENERATED_BUILTIN_PRESETS: ReadonlyArray<GeneratedBuiltinPreset> =
  GENERATED_BUILTIN_TEMPLATES.map((template, index) => ({
    template,
    document: GENERATED_BUILTIN_EXAMPLES[index]!,
  }));
