// Generated by scripts/generate-builtin-presets.ts from presets/builtin/*.textpack.
// Preview documents are separate so ordinary document rendering does not load them.
import type { DocumentSnapshot } from "@/lib/documents/model";

export const GENERATED_BUILTIN_EXAMPLES: ReadonlyArray<DocumentSnapshot> = [
  {
    "schemaVersion": 1,
    "content": {
      "title": "The case for slow publishing",
      "body": "The internet rewards speed. Publish first, correct later, let the feed sort it out. This essay argues the opposite: that the writing worth reading in five years is the writing someone sat on for five weeks.\n\n## The cost of fast\n\nEvery editing pass you skip is a debt the reader pays. A rushed piece externalizes its confusion.\n\n## What slow buys\n\nTime is the only editor that works for free. A draft that survives three weekends of rereading has earned its claims.\n\nWrite fast. Publish slow.",
      "fields": {},
      "tags": [],
      "assets": []
    },
    "presentation": {
      "template": {
        "id": "texttext.article",
        "version": 1
      },
      "theme": {}
    }
  },
  {
    "schemaVersion": 1,
    "content": {
      "title": "Things I keep relearning",
      "body": "- The bug is always in the code you were most sure about\n- Writing the summary first makes the meeting shorter\n- If a file needs a comment to explain its name, rename the file\n- Coffee after 3pm is a loan against tomorrow",
      "fields": {},
      "tags": [],
      "assets": []
    },
    "presentation": {
      "template": {
        "id": "texttext.note",
        "version": 1
      },
      "theme": {}
    }
  },
  {
    "schemaVersion": 1,
    "content": {
      "title": "How Figma’s multiplayer technology works",
      "body": "Figma’s engineering deep-dive on their multiplayer sync: client-side prediction, server-authoritative conflict resolution, and why they chose properties-last-writer-wins over OT. The section on undo in a multiplayer world is the best writing on the topic anywhere.",
      "fields": {
        "sourceUrl": "https://www.figma.com/blog/how-figmas-multiplayer-technology-works/"
      },
      "tags": [],
      "assets": []
    },
    "presentation": {
      "template": {
        "id": "texttext.bookmark",
        "version": 1
      },
      "theme": {}
    }
  },
  {
    "schemaVersion": 1,
    "content": {
      "title": "Nights and weather",
      "body": "Four frames from walks I took instead of writing. The gallery keeps the set together and lets the pictures lead.",
      "fields": {},
      "tags": [],
      "assets": [
        {
          "id": "night-fence",
          "kind": "image",
          "src": "/covers/cover-118.jpg",
          "alt": "The Milky Way over a leaning wooden fence at night",
          "width": 1600,
          "height": 900
        },
        {
          "id": "valley-mist",
          "kind": "image",
          "src": "/covers/cover-119.jpg",
          "alt": "Light falling through mist into a forested mountain valley",
          "width": 1600,
          "height": 900
        },
        {
          "id": "river-bridge",
          "kind": "image",
          "src": "/covers/cover-120.jpg",
          "alt": "A domed cathedral and a footbridge lit above a river at night",
          "width": 1600,
          "height": 900
        },
        {
          "id": "rain-beads",
          "kind": "image",
          "src": "/covers/cover-121.jpg",
          "alt": "Rain beaded across taut grey fabric, close up",
          "width": 1600,
          "height": 900
        }
      ]
    },
    "presentation": {
      "template": {
        "id": "texttext.gallery",
        "version": 1
      },
      "theme": {}
    }
  },
  {
    "schemaVersion": 1,
    "content": {
      "title": "Writing for people who will never meet you",
      "body": "Notes from the talk, written up the same evening while the questions were still fresh.\n\n## The premise\n\nMost technical writing is addressed to the person sitting next to you. The reader who actually shows up is a stranger, two years later, halfway through a bad day.\n\n## What changes\n\nYou stop writing \"obviously\". You define the term the first time. You say what you tried that did not work, because that is the part they cannot reconstruct.\n\n## The question I could not answer\n\nSomeone asked how you write for a stranger without writing for nobody. I still think the answer is that you pick one real person and let the stranger overhear.",
      "fields": {
        "cover": "/covers/cover-119.jpg"
      },
      "tags": [],
      "assets": []
    },
    "presentation": {
      "template": {
        "id": "texttext.talk",
        "version": 1
      },
      "theme": {}
    }
  },
  {
    "schemaVersion": 1,
    "content": {
      "title": "Timeline",
      "body": "",
      "fields": {},
      "tags": [],
      "assets": []
    },
    "presentation": {
      "template": {
        "id": "texttext.timeline",
        "version": 1
      },
      "theme": {}
    }
  },
  {
    "schemaVersion": 1,
    "content": {
      "title": "Rebuilding a studio around live service",
      "body": "A premium studio ships a title, sells it, moves on, and lets the back catalogue quietly die. That model was already failing when I took over the product function, and the catalogue was the asset nobody was managing.\n\n## What changed\n\nI rebuilt the operating model around live service: the roles, the instrumentation, the review cadence. Releases moved from yearly to a biweekly themed cadence, and update pipelines made that cadence sustainable rather than heroic.\n\n## What it produced\n\nThe sharpest proof was a four-year-old title most studios would have sunset. It went back into the top 20 of the US App Store, paid and free. The playbook was repeatable, which is the only reason it counts as a result rather than a story.",
      "fields": {
        "role": "Chief Product Officer, after first leading R&D",
        "caption": "A window in a building nobody was maintaining.",
        "cover": "/covers/cover-201.jpg"
      },
      "tags": [
        "Studio",
        "Product",
        "Live service"
      ],
      "assets": []
    },
    "presentation": {
      "template": {
        "id": "texttext.casestudy",
        "version": 1
      },
      "theme": {}
    }
  },
  {
    "schemaVersion": 1,
    "content": {
      "title": "How we decide what to build",
      "body": "We ship what we can explain to one real person in two sentences. Everything else waits, and most of it never comes back.\n\n## The two sentences\n\nWho is stuck, and what stops being true after we ship. If the second sentence needs a diagram, the idea is not ready.\n\n## What we stopped doing\n\nRoadmap decks. They made us defend last quarter's guesses instead of this week's evidence.\n\n## What replaced them\n\nA page per decision, written before the work starts and edited when it turns out we were wrong.",
      "fields": {
        "icon": "🧭",
        "cover": "/covers/cover-118.jpg"
      },
      "tags": [],
      "assets": []
    },
    "presentation": {
      "template": {
        "id": "texttext.page",
        "version": 1
      },
      "theme": {}
    }
  },
  {
    "schemaVersion": 1,
    "content": {
      "title": "Launch week",
      "body": "Everything that has to happen before Tuesday's announcement. Anything not on this list waits until Thursday.",
      "fields": {
        "area": "work",
        "items": [
          {
            "task": "Freeze the release branch",
            "done": true,
            "when": "2026-07-27",
            "priority": "high"
          },
          {
            "task": "Final pass on the landing page copy",
            "done": true,
            "when": "2026-07-27",
            "priority": "high"
          },
          {
            "task": "Record the 90-second demo",
            "done": false,
            "when": "2026-07-28",
            "priority": "high"
          },
          {
            "task": "Draft the announcement post",
            "done": false,
            "when": "2026-07-28",
            "priority": "medium"
          },
          {
            "task": "Brief the beta list",
            "done": false,
            "when": "2026-07-29",
            "priority": "medium"
          },
          {
            "task": "Order pastries for launch morning",
            "done": false,
            "when": "2026-07-30",
            "priority": "low"
          }
        ]
      },
      "tags": [],
      "assets": []
    },
    "presentation": {
      "template": {
        "id": "texttext.todo",
        "version": 1
      },
      "theme": {}
    }
  },
  {
    "schemaVersion": 1,
    "content": {
      "title": "Website relaunch",
      "body": "Move the marketing site onto the document engine so the site is a workspace and every page is a document.",
      "fields": {
        "status": "active",
        "lead": "Ramine",
        "due": "2026-08-15",
        "milestones": [
          {
            "milestone": "Design locked",
            "due": "2026-08-01",
            "reached": true
          },
          {
            "milestone": "Content migrated",
            "due": "2026-08-08",
            "reached": false
          },
          {
            "milestone": "DNS cutover",
            "due": "2026-08-15",
            "reached": false
          }
        ],
        "tasks": [
          {
            "task": "Audit current pages and traffic",
            "done": true,
            "owner": "Ramine",
            "due": "2026-07-30"
          },
          {
            "task": "Rebuild landing in the engine",
            "done": false,
            "owner": "Mina",
            "due": "2026-08-05"
          },
          {
            "task": "Redirect map for old URLs",
            "done": false,
            "owner": "Jordan",
            "due": "2026-08-12"
          }
        ],
        "risks": "The pricing page A/B test ends Aug 10; cutover before then means migrating the losing variant."
      },
      "tags": [],
      "assets": []
    },
    "presentation": {
      "template": {
        "id": "texttext.project",
        "version": 1
      },
      "theme": {}
    }
  },
  {
    "schemaVersion": 1,
    "content": {
      "title": "Agentic writing launch brief",
      "body": "## Decision\n\nLaunch around one clear promise: TextText turns scattered source material into writing that stays grounded as the source material changes.\n\n## What the product must prove\n\nThe first session starts with real notes, produces a cited brief, and keeps the source-to-claim relationship visible. A writer can revise one claim or passage without asking the agent to regenerate the document.\n\n## Release position\n\nLead with the living brief workflow. Keep provider setup, tool inventories, and advanced automation behind the successful first edit.",
      "fields": {
        "audience": "Writers and product teams evaluating agentic text tools",
        "purpose": "decision",
        "lastReviewed": "2026-08-20",
        "sources": [
          {
            "sourceId": "S1",
            "itemId": "workspace-research-notes",
            "title": "Agentic writing research notes",
            "kind": "workspace",
            "capturedHash": "sha256:research-v3",
            "status": "current",
            "note": "First-session friction and workflow expectations"
          },
          {
            "sourceId": "S2",
            "title": "Paper MCP documentation",
            "kind": "web",
            "url": "https://paper.design/docs/mcp",
            "status": "unverified",
            "note": "Visible verification and task-recipe pattern"
          }
        ],
        "claims": [
          {
            "claimId": "C1",
            "claim": "The first useful result must appear before integration details.",
            "sourceId": "S1",
            "evidence": "Testing repeatedly stalled when setup architecture led the flow.",
            "status": "supported"
          },
          {
            "claimId": "C2",
            "claim": "A visible verification task makes an agent connection understandable.",
            "sourceId": "S2",
            "evidence": "The documentation verifies setup with one concrete canvas action.",
            "status": "supported"
          }
        ],
        "writingRules": [
          {
            "instruction": "Lead with the user outcome, not provider architecture.",
            "scope": "document",
            "enabled": true
          },
          {
            "instruction": "Keep every factual claim traceable to a visible source.",
            "scope": "publication",
            "enabled": true
          },
          {
            "instruction": "Use plain language and short paragraphs.",
            "scope": "selection",
            "enabled": true
          }
        ]
      },
      "tags": [],
      "assets": []
    },
    "presentation": {
      "template": {
        "id": "texttext.brief",
        "version": 1
      },
      "theme": {}
    }
  }
];
