export const DOCUMENT_ENGINE_CSS = String.raw`
.tt-document{--tt-accent:#0071e3;--tt-gap-none:0;--tt-gap-xs:.35rem;--tt-gap-sm:.75rem;--tt-gap-md:1.25rem;--tt-gap-lg:2rem;--tt-gap-xl:3.5rem;--tt-measure:46rem;color:var(--ink,#1d1d1f);background:var(--paper,#fff);min-height:100%;font-family:var(--tt-font,-apple-system,BlinkMacSystemFont,"SF Pro Text","Helvetica Neue",sans-serif)}
.tt-document[data-typography="editorial"]{--tt-font:Iowan Old Style,Palatino Linotype,Book Antiqua,Palatino,serif}
.tt-document[data-typography="mono"]{--tt-font:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace}
.tt-document[data-surface="paper"]{--paper:#fffdf8;--ink:#201f1c;--muted:#6d6a62}.tt-document[data-surface="soft"]{--paper:#f5f5f7}.tt-document[data-surface="ink"]{--paper:#1d1d1f;--ink:#f5f5f7;--muted:#a1a1a6}
.tt-document[data-measure="narrow"]{--tt-measure:36rem}.tt-document[data-measure="wide"]{--tt-measure:64rem}.tt-document[data-measure="full"]{--tt-measure:none}
.tt-document[data-density="compact"]{--tt-gap-sm:.5rem;--tt-gap-md:.85rem;--tt-gap-lg:1.35rem;--tt-gap-xl:2rem}.tt-document[data-density="spacious"]{--tt-gap-sm:1rem;--tt-gap-md:1.75rem;--tt-gap-lg:3rem;--tt-gap-xl:5rem}
.tt-stack,.tt-group,.tt-masthead{display:flex;box-sizing:border-box}.tt-stack[data-direction="vertical"],.tt-group,.tt-masthead{flex-direction:column}.tt-stack[data-direction="horizontal"]{flex-direction:row}.tt-stack,.tt-group{align-items:stretch}.tt-masthead{width:min(var(--tt-measure),calc(100% - 2rem));margin-inline:auto;text-align:center;align-items:center}
.tt-gap-none{gap:var(--tt-gap-none)}.tt-gap-xs{gap:var(--tt-gap-xs)}.tt-gap-sm{gap:var(--tt-gap-sm)}.tt-gap-md{gap:var(--tt-gap-md)}.tt-gap-lg{gap:var(--tt-gap-lg)}.tt-gap-xl{gap:var(--tt-gap-xl)}
.tt-align-start{align-items:flex-start}.tt-align-center{align-items:center}.tt-align-end{align-items:flex-end}.tt-align-stretch{align-items:stretch}
.tt-text{margin:0;overflow-wrap:anywhere}.tt-text-eyebrow,.tt-text-meta{font-size:.75rem;font-weight:600;color:color-mix(in srgb,var(--tt-accent) 60%,var(--ink,#1d1d1f));text-transform:uppercase}.tt-text-title{font-size:clamp(2.5rem,6vw,5.5rem);line-height:.95;font-weight:750}.tt-text-subtitle{font-size:clamp(1.1rem,2.2vw,1.55rem);line-height:1.35;color:var(--muted,#6e6e73)}.tt-text-heading{font-size:1.45rem;line-height:1.15;font-weight:700}.tt-text-body{font-size:1rem;line-height:1.6}.tt-text-caption,.tt-metadata{font-size:.85rem;line-height:1.45;color:var(--muted,#6e6e73)}
.tt-document[data-title-scale="compact"] .tt-text-title{font-size:clamp(2rem,4vw,3.75rem)}.tt-document[data-title-scale="large"] .tt-text-title{font-size:clamp(3rem,8vw,7rem)}
.tt-document[data-alignment="start"] .tt-masthead{text-align:left;align-items:flex-start}.tt-document[data-alignment="start"] .tt-byline,.tt-document[data-alignment="start"] .tt-metadata{justify-content:flex-start}
.tt-prose{width:min(var(--tt-measure),calc(100% - 2rem));margin-inline:auto;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Text","Helvetica Neue",sans-serif;font-size:1.06rem;line-height:1.7;padding-bottom:5rem}.tt-prose>*:first-child{margin-top:0}.tt-prose h1,.tt-prose h2,.tt-prose h3{line-height:1.15;margin:2em 0 .65em}.tt-prose img,.tt-prose video{display:block;max-width:100%;height:auto;margin:1.75rem auto}.tt-prose a{color:color-mix(in srgb,var(--tt-accent) 60%,var(--ink,#1d1d1f));text-underline-offset:.18em}.tt-prose pre{overflow:auto;padding:1rem;background:color-mix(in srgb,var(--ink,#1d1d1f) 7%,transparent)}
.tt-cover,.tt-image,.tt-video{position:relative;overflow:hidden;width:100%;background:color-mix(in srgb,var(--ink,#1d1d1f) 5%,transparent)}.tt-cover img,.tt-cover video,.tt-image img,.tt-video video,.tt-video iframe{display:block;width:100%;height:100%;border:0;object-fit:var(--tt-media-fit,cover)}.tt-height-compact{height:14rem}.tt-height-medium{height:26rem}.tt-height-large{height:min(56vh,42rem)}.tt-height-viewport{height:calc(100vh - 3rem)}
.tt-document[data-media="contained"] .tt-cover,.tt-document[data-media="contained"] .tt-image,.tt-document[data-media="contained"] .tt-video{width:min(64rem,calc(100% - 2rem));margin-inline:auto;border-radius:.5rem}.tt-document[data-media="bleed"] .tt-cover,.tt-document[data-media="bleed"] .tt-image,.tt-document[data-media="bleed"] .tt-video{width:100vw;margin-left:calc(50% - 50vw)}
.tt-byline,.tt-metadata{display:flex;align-items:center;justify-content:center;gap:.5rem;flex-wrap:wrap}.tt-byline-avatar{display:grid;place-items:center;width:2rem;height:2rem;border-radius:50%;background:var(--ink,#1d1d1f);color:var(--paper,#fff);font-size:.75rem;font-weight:700}.tt-byline-separator{color:var(--muted,#6e6e73)}
.tt-gallery{display:grid;grid-template-columns:repeat(var(--tt-gallery-columns,3),minmax(0,1fr));gap:var(--tt-gap-sm);width:100%}.tt-gallery figure{margin:0;min-width:0}.tt-gallery img,.tt-gallery video{display:block;width:100%;aspect-ratio:4/3;object-fit:cover}.tt-gallery figcaption{padding:.5rem 0;color:var(--muted,#6e6e73);font-size:.8rem}
.tt-divider{border:0;border-top:1px solid color-mix(in srgb,var(--ink,#1d1d1f) 16%,transparent);width:min(var(--tt-measure),calc(100% - 2rem));margin:0 auto}.tt-spacer{height:var(--tt-gap-md)}
.tt-document[data-template="texttext.gallery"]>.tt-stack{min-height:100vh}.tt-document[data-template="texttext.gallery"] [data-tt-node="gallery-copy"],.tt-document[data-template="texttext.gallery"] [data-tt-node="gallery-media"]{width:50%;max-height:100vh;overflow:auto;padding:clamp(1rem,4vw,4rem)}
@media(max-width:720px){.tt-stack[data-direction="horizontal"]{flex-direction:column}.tt-document[data-template="texttext.gallery"] [data-tt-node="gallery-copy"],.tt-document[data-template="texttext.gallery"] [data-tt-node="gallery-media"]{width:100%;max-height:none}.tt-text-title{font-size:clamp(2.3rem,13vw,4rem)}.tt-height-large{height:38vh}}
@media(prefers-color-scheme:dark){.tt-document{--ink:#f5f5f7;--paper:#1c1c1e;--muted:#a1a1a6}}
@media(prefers-reduced-motion:reduce){.tt-document *{scroll-behavior:auto!important;transition-duration:.01ms!important;animation-duration:.01ms!important;animation-iteration-count:1!important}}
`;
