// Generated by: swift run --package-path mac capability-generator --manifest mac/Resources/AppCapabilities.yaml --output-root .
// Do not edit by hand.

import XCTest
@testable import TextTextAppIntents

final class GeneratedCapabilityTests: XCTestCase {
    func testDeclaredIntentImplementationsAreRegistered() throws {
        if #available(macOS 13.0, *) {
            XCTAssertEqual(CapabilityCatalog.missingImplementationIdentifiers, [])
        }
    }

    func testManifestCountsMatchGeneratedCatalog() throws {
        XCTAssertEqual(CapabilityCatalog.entities.count, 5)
        XCTAssertEqual(CapabilityCatalog.intents.count, 10)
    }
}
