// Browser-safe built-in data generated from the checked-in TextPacks.
// Run with --check to verify the committed module without changing files.

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseTextpack } from "../src/lib/github/textpack";
import { validateDocumentSnapshot } from "../src/lib/documents/model";
import { parsePostMarkdownFile } from "../src/lib/markdown-files";
import { normalizeTags } from "../src/lib/tags";
import { validateTemplateDefinition } from "../src/lib/presentation/schema";
import { validatedLookSource } from "../src/lib/presentation/template-library";
import { builtinBrowserDocument } from "./builtin-preset-assets";

const root = process.cwd();
const presetDirectory = join(root, "presets", "builtin");
const presentationDirectory = join(root, "src", "lib", "presentation");

// Preserve the gallery and default-picker order. The render definitions and
// example documents themselves come only from the TextPacks below.
const slugs = [
  "article",
  "note",
  "bookmark",
  "gallery",
  "talk",
  "timeline",
  "casestudy",
  "page",
  "todo",
  "project",
  "brief",
] as const;

const packFiles = readdirSync(presetDirectory)
  .filter((name) => name.endsWith(".textpack"))
  .sort();
const expectedFiles = slugs.map((slug) => `${slug}.textpack`).sort();
if (JSON.stringify(packFiles) !== JSON.stringify(expectedFiles)) {
  throw new Error("Built-in TextPack filenames differ from the active catalog.");
}

const presets = slugs.map((slug) => {
  const bytes = readFileSync(join(presetDirectory, `${slug}.textpack`));
  const parts = parseTextpack(bytes);
  if (!parts.template) throw new Error(`${slug}: missing template.json`);
  if (!parts.markdown.trim()) throw new Error(`${slug}: empty text.md`);
  const template = validateTemplateDefinition(parts.template);
  const document = validateDocumentSnapshot(parts.document);
  const markdown = parsePostMarkdownFile(parts.markdown);
  if (template.id !== `texttext.${slug}` || template.version !== 1) {
    throw new Error(`${slug}: unexpected built-in look identity`);
  }
  if (
    document.presentation.template.id !== template.id ||
    document.presentation.template.version !== template.version
  ) {
    throw new Error(`${slug}: document.json does not pin template.json`);
  }
  if (
    markdown.fields.title !== document.content.title ||
    markdown.body.trimEnd() !== document.content.body.trimEnd() ||
    JSON.stringify(markdown.fields.tags ?? []) !==
      JSON.stringify(normalizeTags(document.content.tags))
  ) {
    throw new Error(`${slug}: text.md disagrees with document.json`);
  }
  if (parts.templateAuthoringSource) {
    validatedLookSource(template, parts.templateAuthoringSource);
  }
  return { template, document: validateDocumentSnapshot(builtinBrowserDocument(bytes, document, root)) };
});

const templateOutput = `// Generated by scripts/generate-builtin-presets.ts from presets/builtin/*.textpack.
// Edit the TextPack files, then regenerate this browser-safe module.
import type { TemplateDefinition } from "@/lib/presentation/schema";

export const GENERATED_BUILTIN_TEMPLATES: ReadonlyArray<TemplateDefinition> = ${JSON.stringify(presets.map((entry) => entry.template), null, 2)};
`;

const exampleOutput = `// Generated by scripts/generate-builtin-presets.ts from presets/builtin/*.textpack.
// Preview documents are separate so ordinary document rendering does not load them.
import type { DocumentSnapshot } from "@/lib/documents/model";

export const GENERATED_BUILTIN_EXAMPLES: ReadonlyArray<DocumentSnapshot> = ${JSON.stringify(presets.map((entry) => entry.document), null, 2)};
`;

const presetOutput = `// Generated by scripts/generate-builtin-presets.ts from presets/builtin/*.textpack.
// This facade pairs definitions and previews only in consumers that need both.
import type { DocumentSnapshot } from "@/lib/documents/model";
import type { TemplateDefinition } from "@/lib/presentation/schema";
import { GENERATED_BUILTIN_EXAMPLES } from "./generated-builtin-examples";
import { GENERATED_BUILTIN_TEMPLATES } from "./generated-builtin-templates";

export type GeneratedBuiltinPreset = {
  template: TemplateDefinition;
  document: DocumentSnapshot;
};

export const GENERATED_BUILTIN_PRESETS: ReadonlyArray<GeneratedBuiltinPreset> =
  GENERATED_BUILTIN_TEMPLATES.map((template, index) => ({
    template,
    document: GENERATED_BUILTIN_EXAMPLES[index]!,
  }));
`;

// Swift embeds the same definitions so standalone app/CLI creation never
// depends on a server, source checkout, or a separately copied resource bundle.
const swiftOutput = `// Generated by scripts/generate-builtin-presets.ts from presets/builtin/*.textpack.
// Edit the TextPacks, then run npm run presets:generate.
import Foundation

enum GeneratedBuiltinTemplates {
    static let json = #"""
${JSON.stringify(presets.map((entry) => entry.template), null, 2)}
"""#
}
`;
const swiftPath = join(root, "mac", "Sources", "TextTextFileProviderKit", "GeneratedBuiltinTemplates.swift");

const outputs = [
  ["generated-builtin-templates.ts", templateOutput],
  ["generated-builtin-examples.ts", exampleOutput],
  ["generated-builtin-presets.ts", presetOutput],
] as const;

if (process.argv.includes("--check")) {
  for (const [filename, output] of outputs) {
    if (readFileSync(join(presentationDirectory, filename), "utf8") !== output) {
      throw new Error(
        `${filename} differs from its TextPacks. Run npm run presets:generate.`,
      );
    }
  }
  if (readFileSync(swiftPath, "utf8") !== swiftOutput) {
    throw new Error("GeneratedBuiltinTemplates.swift differs from its TextPacks. Run npm run presets:generate.");
  }
  console.log(`Checked ${presets.length} built-in TextPacks and generated modules.`);
} else {
  for (const [filename, output] of outputs) {
    writeFileSync(join(presentationDirectory, filename), output);
  }
  writeFileSync(swiftPath, swiftOutput);
  console.log(`Generated ${presets.length} built-in presets from TextPacks.`);
}
