// Regenerate mac/health-checks.json from the canonical Swift list.
//
// The set of health checks a release must report used to be written out three
// times, in three languages: the Swift source, the Swift test, and the bash
// release gate. Retiring one check meant three separate failed releases, each
// revealing the next stale copy. Now `WriteHealthChecks.required` in
// AppHealthReporter.swift is the single source, and both other consumers read
// the JSON this produces.
//
//   npx tsx scripts/sync-health-checks.ts          regenerate
//   npx tsx scripts/sync-health-checks.ts --check   fail if stale (release gate)

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { repositoryRoot } from "./work-unit";

const SOURCE = "mac/Sources/Write/AppHealthReporter.swift";
const CAPABILITY_SOURCE = "mac/scripts/workflow-capability-eval.ts";
const MANIFEST = "mac/health-checks.json";

/** Pull the string literals out of `WriteHealthChecks.required`, resolving the
 * `WriteWorkflowHealth.*` constants to their values so the manifest is literal. */
function canonicalChecks(): string[] {
  const swift = readFileSync(join(repositoryRoot, SOURCE), "utf8");

  const workflow = new Map<string, string>();
  const workflowBlock = swift.slice(swift.indexOf("enum WriteWorkflowHealth {"));
  for (const [, name, value] of workflowBlock.matchAll(
    /static let (\w+) = "([\w.]+)"/g,
  )) {
    workflow.set(name, value);
  }

  const start = swift.indexOf("static let required = [");
  if (start < 0) throw new Error(`Could not find WriteHealthChecks.required in ${SOURCE}`);
  const body = swift.slice(start, swift.indexOf("]", start));

  const checks: string[] = [];
  for (const line of body.split("\n").slice(1)) {
    const literal = line.match(/"([\w.]+)"/);
    if (literal) {
      checks.push(literal[1]);
      continue;
    }
    const reference = line.match(/WriteWorkflowHealth\.(\w+)/);
    if (reference) {
      const value = workflow.get(reference[1]);
      if (!value) throw new Error(`Unknown WriteWorkflowHealth.${reference[1]}`);
      checks.push(value);
    }
  }
  if (checks.length === 0) throw new Error("Parsed an empty health check list");
  return checks;
}

/** The destructive web workflows that must produce a signed capability receipt.
 * The eval that runs them is the source; the attestation script used to keep its
 * own copy of this set, which is a third place for it to drift. */
function capabilityWorkflows(): string[] {
  const source = readFileSync(join(repositoryRoot, CAPABILITY_SOURCE), "utf8");
  const ids = [...source.matchAll(/id:\s*"(workflow\.[\w.]+)"/g)].map(
    (match) => match[1],
  );
  if (ids.length === 0) {
    throw new Error(`Parsed no workflow ids from ${CAPABILITY_SOURCE}`);
  }
  return [...new Set(ids)].sort();
}

const checks = canonicalChecks();
const capabilities = capabilityWorkflows();

// A capability workflow that the app never reports is a receipt nobody checks.
const missing = capabilities.filter((id) => !checks.includes(id));
if (missing.length > 0) {
  throw new Error(
    `${CAPABILITY_SOURCE} evaluates ${missing.join(", ")}, but ${SOURCE} does not require them.`,
  );
}

const rendered = `${JSON.stringify(
  {
    comment:
      "Generated by scripts/sync-health-checks.ts. Do not edit by hand. `required` comes from WriteHealthChecks.required in AppHealthReporter.swift; `capabilityWorkflows` comes from mac/scripts/workflow-capability-eval.ts.",
    required: checks,
    capabilityWorkflows: capabilities,
  },
  null,
  2,
)}\n`;

const manifestPath = join(repositoryRoot, MANIFEST);
if (process.argv.includes("--check")) {
  const current = (() => {
    try {
      return readFileSync(manifestPath, "utf8");
    } catch {
      return "";
    }
  })();
  if (current !== rendered) {
    console.error(
      `${MANIFEST} is stale. Run: npx tsx scripts/sync-health-checks.ts`,
    );
    process.exit(1);
  }
  console.log(
    JSON.stringify({
      status: "current",
      checks: checks.length,
      capabilityWorkflows: capabilities.length,
    }),
  );
} else {
  writeFileSync(manifestPath, rendered, "utf8");
  console.log(
    JSON.stringify({
      status: "written",
      checks: checks.length,
      capabilityWorkflows: capabilities.length,
    }),
  );
}
