using TextText.Core;
using System.IO.Compression;
using System.Text;
using System.Text.Json;
static class Test
{
 static void Assert(bool condition,string label){if(!condition)throw new Exception(label);Console.WriteLine("PASS "+label);}
 static void Throws<T>(Action action,string label) where T:Exception {try{action();}catch(T){Console.WriteLine("PASS "+label);return;}throw new Exception(label);}
 static byte[] Pack(string body="hello",string id="test-1") {using var output=new MemoryStream();using(var zip=new ZipArchive(output,ZipArchiveMode.Create,true)){using(var w=new StreamWriter(zip.CreateEntry("text.md").Open()))w.Write("---\ntextTextId: \""+id+"\"\n---\n"+body);using(var w=new StreamWriter(zip.CreateEntry("unknown.bin").Open()))w.Write("opaque-original");}return output.ToArray();}
 static async Task Main(){var temporaryRoot=Path.GetTempPath();if(OperatingSystem.IsMacOS()&&temporaryRoot.StartsWith("/var/"))temporaryRoot="/private"+temporaryRoot;var temp=Path.Combine(temporaryRoot,"texttext-core-test-"+Guid.NewGuid());Directory.CreateDirectory(temp);try{
 var store=new TextPackStore(Path.Combine(temp,"workspace"),Path.Combine(temp,"device"));
 Throws<IOException>(()=>store.Resolve("../outside.textpack"),"reject traversal");Throws<IOException>(()=>store.Resolve("Notes/a.textpack:stream"),"reject alternate data streams");
 var first=store.Write("Notes/Test.textpack",Pack());Assert(first.ItemId=="test-1","identity extraction");
 var macFolder=Path.Combine(temp,"mac-folder");Directory.CreateDirectory(Path.Combine(macFolder,".texttext","sync"));
 var macJournal=Path.Combine(macFolder,".texttext","sync","state.json");
 File.WriteAllText(macJournal,"{\"binding\":{\"origin\":\"https://TEXTTEXT.app\",\"workspaceId\":\"workspace-a\"},\"cursor\":900,\"outbox\":{}}");
 var originalMacJournal=File.ReadAllText(macJournal);
 Assert(WorkspaceLocation.Validate(macFolder,"https://texttext.app/","workspace-a")==macFolder,"Mac legacy binding canonicalizes origin");
 WorkspaceLocation.Bind(macFolder,"https://texttext.app/","workspace-a");
 Assert(File.ReadAllText(macJournal)==originalMacJournal,"Mac foreign cursor and outbox remain untouched");
 Throws<IOException>(()=>WorkspaceLocation.Validate(macFolder,"https://texttext.app","workspace-b"),"Mac legacy binding rejects other workspace");
 Assert(File.ReadAllText(Path.Combine(macFolder,".texttext","workspace-binding.json")).Contains("\"workspaceId\""),"portable binding uses shared camelCase schema");
 var alternate=Path.Combine(temp,"alternate");Directory.CreateDirectory(alternate);
 WorkspaceLocation.Bind(alternate,"https://texttext.app/","workspace-a");
 Assert(WorkspaceLocation.Validate(alternate,"https://texttext.app/","workspace-a")==alternate,"workspace location validates saved binding");
 Throws<IOException>(()=>WorkspaceLocation.Validate(alternate,"https://texttext.app/","workspace-b"),"workspace location rejects other workspace");
 Throws<IOException>(()=>WorkspaceLocation.Validate(alternate,"https://other.example/","workspace-a"),"workspace location rejects other server");
 File.WriteAllText(Path.Combine(alternate,".texttext","workspace-binding.json"),"{bad");
 Throws<IOException>(()=>WorkspaceLocation.Validate(alternate,"https://texttext.app/","workspace-a"),"workspace location preserves corrupt binding");
 Assert(FileActivation.Resolve(store,Path.Combine(store.Root,"Notes","Test.textpack"))==first.Path,"activation resolves existing workspace pack");
 Throws<IOException>(()=>FileActivation.Resolve(store,Path.Combine(temp,"outside.textpack")),"activation rejects outside workspace");
 Throws<IOException>(()=>FileActivation.Resolve(store,"Notes/Test.textpack"),"activation rejects relative arguments");
 Throws<IOException>(()=>FileActivation.Resolve(store,Path.Combine(store.Root,"Notes","Test.md")),"activation rejects non TextPack arguments");
 Throws<FileNotFoundException>(()=>FileActivation.Resolve(store,Path.Combine(store.Root,"Notes","missing.textpack")),"activation rejects missing pack");
 Throws<FileChangedException>(()=>store.Write(first.Path,Pack("overwrite"),"stale"),"stale write rejected");
 var changed=store.UpdateMarkdown(first.Path,"---\ntextTextId: \"test-1\"\n---\nmodified",first.Hash);
 using(var zip=new ZipArchive(new MemoryStream(store.Read(first.Path))))using(var reader=new StreamReader(zip.GetEntry("unknown.bin")!.Open()))Assert(reader.ReadToEnd()=="opaque-original","opaque assets preserved");
 var transport=new Fake();var engine=new SyncEngine(store,transport);await engine.SyncAsync();Assert(transport.UploadCount==1,"initial upload");await engine.SyncAsync();Assert(transport.UploadCount==1,"idle pass has no uploads");
 var current=store.Describe(first.Path);store.UpdateMarkdown(first.Path,TextPackStore.Markdown(store.Read(first.Path))+"\nexternal",current.Hash);
 transport.FailAfterCommit=true;try{await engine.SyncAsync();throw new Exception("expected lost ACK");}catch(HttpRequestException){}
 var operations=transport.Operations.ToArray();await new SyncEngine(store,transport).SyncAsync(localChangesOnly:true);Assert(transport.Operations.Last()==operations.Last(),"lost ACK replays same durable operation ID");Assert(transport.UploadCount==2,"replay applies exactly once");
 current=store.Describe(first.Path);store.Rename(first.Path,"Notes/Renamed.textpack",current.Hash);await new SyncEngine(store,transport).SyncAsync();Assert(transport.Item!.RelativePath=="Notes/Renamed.textpack","rename sync survives engine restart");
 File.Move(store.Resolve("Notes/Renamed.textpack"),Path.Combine(temp,"evicted.textpack"));await engine.SyncAsync();Assert(transport.DeleteCount==0,"missing provider file is not deletion");File.Move(Path.Combine(temp,"evicted.textpack"),store.Resolve("Notes/Renamed.textpack"));
 current=store.Describe("Notes/Renamed.textpack");store.Delete(current.Path,current.Hash);await new SyncEngine(store,transport).SyncAsync();Assert(transport.DeleteCount==1,"explicit delete survives restart");Assert(Directory.GetFiles(Path.Combine(store.StateDirectory,"recovery"),"trash-*").Length==1,"delete preserves recoverable bytes");
 File.WriteAllText(Path.Combine(store.StateDirectory,"sync.json"),"{\"Version\":999}");try{await engine.SyncAsync();throw new Exception("future state accepted");}catch(InvalidDataException){}Assert(File.ReadAllText(Path.Combine(store.StateDirectory,"sync.json")).Contains("999"),"future state fails closed without rewriting");

 var other=new TextPackStore(Path.Combine(temp,"second"),Path.Combine(temp,"second-device"));var otherTransport=new Fake();var otherEngine=new SyncEngine(other,otherTransport);
 var seed=other.Write("Notes/Concurrent.textpack",Pack());await otherEngine.SyncAsync();
 other.UpdateMarkdown(seed.Path,TextPackStore.Markdown(other.Read(seed.Path))+" local",other.Describe(seed.Path).Hash);
 otherTransport.Data=Pack("remote");otherTransport.Item=otherTransport.Item! with{Revision=TextPackStore.Hash(otherTransport.Data)};
 await otherEngine.SyncAsync();Assert(otherEngine.Status.Error!=null,"conflict reports retained copies");
 Assert(TextPackStore.Markdown(other.Read(seed.Path)).EndsWith(" local"),"conflict preserves current local document");
 Assert(Directory.GetFiles(Path.Combine(other.StateDirectory,"recovery"),"remote-conflict-*").Length==1,"conflict preserves remote document");
 var resumed=new TextPackStore(Path.Combine(temp,"incoming"),Path.Combine(temp,"incoming-device"));var payload=Pack("downloaded");resumed.Write("Notes/Moved.textpack",payload);
 var state=new SyncEngine.State{PendingPull=new("test-1","Notes/Moved.textpack","Notes/Old.textpack","oldhash",TextPackStore.Hash(payload),Convert.ToBase64String(payload))};
 TextPackStore.AtomicWrite(Path.Combine(resumed.StateDirectory,"sync.json"),JsonSerializer.SerializeToUtf8Bytes(state));
 var resumedTransport=new Fake{Item=new("test-1","Notes/Moved.textpack",TextPackStore.Hash(payload)),Data=payload};await new SyncEngine(resumed,resumedTransport).SyncAsync(localChangesOnly:true);
 Assert(resumedTransport.UploadCount==0,"interrupted incoming apply resumes without reupload");
 var fenced=new TextPackStore(Path.Combine(temp,"fenced"),Path.Combine(temp,"fenced-device"));var ft=new Fake();var fe=new SyncEngine(fenced,ft);var ff=fenced.Write("Notes/Edit.textpack",Pack());await fe.SyncAsync();
 using(var lease=await fe.AcquireCollaborationAsync("test-1")){var updated=fenced.UpdateMarkdown(ff.Path,TextPackStore.Markdown(fenced.Read(ff.Path))+" collaborative",fenced.Describe(ff.Path).Hash);await fe.SyncAsync();Assert(ft.UploadCount==1,"active collaboration fences file upload");ft.Data=fenced.Read(ff.Path);ft.Item=ft.Item! with{Revision=updated.Hash};await fe.AcknowledgeCheckpointAsync("test-1",ff.Path,updated.Hash,updated.Hash);}
 await fe.SyncAsync();Assert(ft.UploadCount==1,"acknowledged checkpoint avoids duplicate upload");
 var encoded=Pack();using(var ms=new MemoryStream()) {using(var z=new ZipArchive(ms,ZipArchiveMode.Create,true))using(var original=new ZipArchive(new MemoryStream(encoded)))foreach(var e in original.Entries.Reverse()){var copy=z.CreateEntry(e.FullName,CompressionLevel.NoCompression);using var dst=copy.Open();using var src=e.Open();src.CopyTo(dst);}Assert(TextPackStore.Equivalent(encoded,ms.ToArray()),"ZIP encoding changes preserve logical equality");}
 var sharedTransport=new Fake();var sharedFiles=new TextPackStore(Path.Combine(temp,"shared"),Path.Combine(temp,"shared-device"));var initial=sharedFiles.Write("Notes/Shared.textpack",Pack());var sharedSync=new SyncEngine(sharedFiles,sharedTransport);await sharedSync.SyncAsync();
 using(var shared=new SharedEditingStore(sharedFiles,sharedSync)) {
 var firstSession=await shared.OpenAsync("test-1",initial.Path,sharedFiles.Describe(initial.Path).Hash);var secondSession=await shared.OpenAsync("test-1",initial.Path,firstSession.Document.Hash);shared.Close(firstSession.SessionToken);
 var content=Pack("shared-pending");var cp=new SharedCheckpoint("test-1",initial.Path,TextPackStore.Hash(content),sharedTransport.Item!.Revision,1,0,1,JsonSerializer.Serialize(new{version=1,epoch=1,seq=0,journalGeneration=1,revision=sharedTransport.Item.Revision,relativePath=initial.Path,update="AAA=",pending=new[]{"AAA="}}),true);
 await shared.CheckpointAsync(secondSession.SessionToken,secondSession.Document.Hash,content,cp);Assert(TextPackStore.Markdown(sharedFiles.Read(initial.Path)).EndsWith("shared-pending"),"late close cannot invalidate replacement session");
 try{await shared.CheckpointAsync(firstSession.SessionToken,secondSession.Document.Hash,content,cp);throw new Exception("stale session accepted");}catch(InvalidOperationException){}
 shared.Close(secondSession.SessionToken);await sharedSync.SyncAsync();Assert(sharedTransport.UploadCount==1,"pending journal fences file sync after close");
 using var restarted=new SharedEditingStore(sharedFiles,sharedSync);var recovered=await restarted.OpenAsync("test-1",initial.Path,sharedFiles.Describe(initial.Path).Hash);Assert(recovered.Checkpoint?.Journal==cp.Journal,"pending shared journal survives restart");
 var invalid=cp with{Version=99};try{await restarted.CheckpointAsync(recovered.SessionToken,recovered.Document.Hash,content,invalid);throw new Exception("future checkpoint accepted");}catch(InvalidDataException){}
 Assert(JsonSerializer.Deserialize<SharedCheckpoint>(File.ReadAllText(Path.Combine(sharedFiles.StateDirectory,"shared-editing","test-1","checkpoint.json")))!.Journal==cp.Journal,"unknown checkpoint version does not erase retained state");
 }
 var isolated=new TextPackStore(Path.Combine(temp,"isolated"),Path.Combine(temp,"isolated-device"));var many=new Many();var isolatedSync=new SyncEngine(isolated,many);
 var one=isolated.Write("Notes/One.textpack",Pack("one","one"));var two=isolated.Write("Notes/Two.textpack",Pack("two","two"));await isolatedSync.SyncAsync();
 isolated.UpdateMarkdown(one.Path,TextPackStore.Markdown(isolated.Read(one.Path))+" local",isolated.Describe(one.Path).Hash);isolated.UpdateMarkdown(two.Path,TextPackStore.Markdown(isolated.Read(two.Path))+" local",isolated.Describe(two.Path).Hash);
 many.Items["one"].Data=Pack("remote","one");many.Items["one"].Item=many.Items["one"].Item! with{Revision=TextPackStore.Hash(many.Items["one"].Data)};
 await isolatedSync.SyncAsync();Assert(many.Items["two"].UploadCount==2,"conflicting item does not block unrelated file sync");Assert(!await isolatedSync.IsReadyAsync("one")&&await isolatedSync.IsReadyAsync("two"),"readiness reflects per-item durability");
 using(var recoveryStore=new SharedEditingStore(sharedFiles,sharedSync)){var session=await recoveryStore.OpenAsync("test-1",initial.Path,sharedFiles.Describe(initial.Path).Hash);var recovery=sharedFiles.Write("Notes/Recovery.textpack",Pack("preserved shared edits","recovered-id"));await recoveryStore.RecoverAsync(session.SessionToken,recovery.Path,recovery.Hash);Assert(!SharedEditingStore.HasProtectedState(sharedFiles.StateDirectory,"test-1"),"explicit verified recovery releases protected journal");Assert(Directory.GetDirectories(Path.Combine(sharedFiles.StateDirectory,"shared-editing","test-1"),"archive-*").Length==1,"recovery archives previous shared journal");}
 var beforeCrash=sharedFiles.Describe(initial.Path);var crashBytes=Pack("crash-recovered");var crashRevision=sharedTransport.Item!.Revision;
 var crashCheckpoint=new SharedCheckpoint("test-1",initial.Path,TextPackStore.Hash(crashBytes),crashRevision,1,0,2,JsonSerializer.Serialize(new{version=1,epoch=1,seq=0,journalGeneration=2,revision=crashRevision,relativePath=initial.Path,update="AAA=",pending=new[]{"AAA="}}),true);
 TextPackStore.AtomicWrite(Path.Combine(sharedFiles.StateDirectory,"shared-editing","test-1","intent.json"),JsonSerializer.SerializeToUtf8Bytes(new{Version=1,BeforeHash=beforeCrash.Hash,Payload=Convert.ToBase64String(crashBytes),Checkpoint=crashCheckpoint}));
 using(var crashRecovery=new SharedEditingStore(sharedFiles,sharedSync)){var opened=await crashRecovery.OpenAsync("test-1",initial.Path,beforeCrash.Hash);Assert(opened.Document.Hash==TextPackStore.Hash(crashBytes)&&opened.Checkpoint?.Pending==true,"journal-first interrupted materialization resumes after restart");}
 var initialEquivalent=new TextPackStore(Path.Combine(temp,"equivalent"),Path.Combine(temp,"equivalent-device"));var eqBytes=Pack();var eqLocal=initialEquivalent.Write("Notes/Equal.textpack",eqBytes);byte[] differentlyEncoded;
 using(var stream=new MemoryStream()){using(var zip=new ZipArchive(stream,ZipArchiveMode.Create,true))using(var original=new ZipArchive(new MemoryStream(eqBytes)))foreach(var entry in original.Entries.Reverse()){using var to=zip.CreateEntry(entry.FullName,CompressionLevel.NoCompression).Open();using var from=entry.Open();from.CopyTo(to);}differentlyEncoded=stream.ToArray();}
 var eqTransport=new Fake{Data=differentlyEncoded,Item=new("test-1",eqLocal.Path,TextPackStore.Hash(differentlyEncoded))};var eqEngine=new SyncEngine(initialEquivalent,eqTransport);await eqEngine.SyncAsync();Assert(eqTransport.UploadCount==0&&await eqEngine.IsReadyAsync("test-1"),"equivalent initial archive adopts baseline without upload and is ready");Assert(await eqEngine.BaselineRevisionAsync("test-1")==TextPackStore.Hash(differentlyEncoded)&&initialEquivalent.Describe(eqLocal.Path).Hash==eqLocal.Hash,"equivalent archive tracks separate server revision and local hash");
 using(var replay=new SharedEditingStore(sharedFiles,sharedSync)){var opened=await replay.OpenAsync("test-1",initial.Path,sharedFiles.Describe(initial.Path).Hash);var checkpoint=opened.Checkpoint!;var result=await replay.CheckpointAsync(opened.SessionToken,opened.Document.Hash,sharedFiles.Read(initial.Path),checkpoint);Assert(result.Hash==opened.Document.Hash,"same generation checkpoint replay is idempotent");var oldJournal=System.Text.Json.Nodes.JsonNode.Parse(checkpoint.Journal)!;oldJournal["journalGeneration"]=checkpoint.JournalGeneration-1;try{await replay.CheckpointAsync(opened.SessionToken,result.Hash,sharedFiles.Read(initial.Path),checkpoint with{JournalGeneration=checkpoint.JournalGeneration-1,Journal=oldJournal.ToJsonString()});throw new Exception("old generation accepted");}catch(InvalidOperationException){}Assert(sharedFiles.Describe(initial.Path).Hash==result.Hash,"stale generation cannot rewrite shared projection");}
 var externalCurrent=sharedFiles.Describe(initial.Path);sharedFiles.UpdateMarkdown(initial.Path,TextPackStore.Markdown(sharedFiles.Read(initial.Path))+" external-agent",externalCurrent.Hash);
 using(var externalReopen=new SharedEditingStore(sharedFiles,sharedSync)){var opened=await externalReopen.OpenAsync("test-1",initial.Path,sharedFiles.Describe(initial.Path).Hash);Assert(opened.Checkpoint?.RetiredReason!=null&&opened.Checkpoint.Pending,"external edit retires pending journal instead of replaying stale content");Assert(TextPackStore.Markdown(sharedFiles.Read(initial.Path)).EndsWith(" external-agent"),"external content remains intact when old journal is retired");}
 var interrupted=new TextPackStore(Path.Combine(temp,"interrupted-external"),Path.Combine(temp,"interrupted-external-device"));var interruptedInitial=interrupted.Write("Notes/Changed.textpack",Pack("before"));var remoteIncoming=Pack("remote-after");interrupted.UpdateMarkdown(interruptedInitial.Path,TextPackStore.Markdown(interrupted.Read(interruptedInitial.Path))+" external",interruptedInitial.Hash);
 interrupted.Write("Notes/Other.textpack",Pack("other","other"));var incomingState=new SyncEngine.State{PendingPull=new("test-1",interruptedInitial.Path,interruptedInitial.Path,interruptedInitial.Hash,TextPackStore.Hash(remoteIncoming),Convert.ToBase64String(remoteIncoming))};TextPackStore.AtomicWrite(Path.Combine(interrupted.StateDirectory,"sync.json"),JsonSerializer.SerializeToUtf8Bytes(incomingState));var incomingTransport=new Many();incomingTransport.Items["test-1"]=new Fake{Data=remoteIncoming,Item=new("test-1",interruptedInitial.Path,TextPackStore.Hash(remoteIncoming))};var incomingEngine=new SyncEngine(interrupted,incomingTransport);await incomingEngine.SyncAsync();Assert(TextPackStore.Markdown(interrupted.Read(interruptedInitial.Path)).EndsWith(" external")&&incomingTransport.Items["other"].UploadCount==1,"external edit during interrupted pull preserves both versions and unrelated sync proceeds");
 var acknowledgedStore=new TextPackStore(Path.Combine(temp,"acknowledged-external"),Path.Combine(temp,"acknowledged-device"));var acknowledgedFile=acknowledgedStore.Write("Notes/Ack.textpack",Pack());var acknowledgedTransport=new Fake();var acknowledgedEngine=new SyncEngine(acknowledgedStore,acknowledgedTransport);await acknowledgedEngine.SyncAsync();
 using(var acknowledgedEditing=new SharedEditingStore(acknowledgedStore,acknowledgedEngine)){var opened=await acknowledgedEditing.OpenAsync("test-1",acknowledgedFile.Path,acknowledgedStore.Describe(acknowledgedFile.Path).Hash);var acknowledgedBytes=Pack("acknowledged");var revision=TextPackStore.Hash(acknowledgedBytes);var cp=new SharedCheckpoint("test-1",acknowledgedFile.Path,revision,revision,1,1,1,JsonSerializer.Serialize(new{version=1,epoch=1,seq=1,journalGeneration=1,revision,relativePath=acknowledgedFile.Path,update="AAA=",pending=Array.Empty<string>()}),false);acknowledgedTransport.Data=acknowledgedBytes;acknowledgedTransport.Item=acknowledgedTransport.Item! with{Revision=revision};await acknowledgedEditing.CheckpointAsync(opened.SessionToken,opened.Document.Hash,acknowledgedBytes,cp);}
 acknowledgedStore.UpdateMarkdown(acknowledgedFile.Path,TextPackStore.Markdown(acknowledgedStore.Read(acknowledgedFile.Path))+" agent",acknowledgedStore.Describe(acknowledgedFile.Path).Hash);await acknowledgedEngine.SyncAsync();using(var reopenedAck=new SharedEditingStore(acknowledgedStore,acknowledgedEngine)){var opened=await reopenedAck.OpenAsync("test-1",acknowledgedFile.Path,acknowledgedStore.Describe(acknowledgedFile.Path).Hash);Assert(opened.Checkpoint==null,"acknowledged stale journal archived after external edit without spurious recovery");}
 var tombstoneStore=new TextPackStore(Path.Combine(temp,"tombstone-conflict"),Path.Combine(temp,"tombstone-conflict-device"));var tombstoneTransport=new Many();var tombstoneEngine=new SyncEngine(tombstoneStore,tombstoneTransport);var doomed=tombstoneStore.Write("Notes/Doomed.textpack",Pack("doomed","doomed"));await tombstoneEngine.SyncAsync();tombstoneStore.UpdateMarkdown(doomed.Path,TextPackStore.Markdown(tombstoneStore.Read(doomed.Path))+" edited",tombstoneStore.Describe(doomed.Path).Hash);tombstoneTransport.Items["doomed"].Item=tombstoneTransport.Items["doomed"].Item! with{Revision="remote-changed"};tombstoneTransport.Items["doomed"].DownloadFailure=System.Net.HttpStatusCode.NotFound;tombstoneStore.Write("Notes/Survivor.textpack",Pack("survivor","survivor"));await tombstoneEngine.SyncAsync();Assert(tombstoneEngine.Status.Error!=null&&tombstoneTransport.Items["survivor"].UploadCount==1,"conflict with missing remote bytes fences only the affected item");
 var notifyStore=new TextPackStore(Path.Combine(temp,"ack-notify"),Path.Combine(temp,"ack-notify-state"));var notifyPack=notifyStore.Write("Notes/Notify.textpack",Pack("before","notify"));var notifyRemote=new Fake();var notifyEngine=new SyncEngine(notifyStore,notifyRemote);await notifyEngine.SyncAsync();var durableEvents=0;notifyEngine.DurabilityChanged+=()=>durableEvents++;
 notifyStore.UpdateMarkdown(notifyPack.Path,TextPackStore.Markdown(notifyStore.Read(notifyPack.Path))+" changed",notifyStore.Describe(notifyPack.Path).Hash);Assert(!await notifyEngine.IsReadyAsync("notify"),"changed file waits for upload acknowledgement");var fileEvents=0;notifyStore.Changed+=()=>fileEvents++;await notifyEngine.SyncAsync();Assert(await notifyEngine.IsReadyAsync("notify")&&durableEvents>0&&fileEvents==0,"own upload ACK emits durable readiness event without rewriting file");durableEvents=0;await notifyEngine.SyncAsync();Assert(durableEvents==0,"idle sync emits no durable change notification");
 var cadenceStore=new TextPackStore(Path.Combine(temp,"cadence"),Path.Combine(temp,"cadence-state"));var cadenceFile=cadenceStore.Write("Notes/Cadence.textpack",Pack("initial","cadence"));var cadenceRemote=new Fake();var cadenceEngine=new SyncEngine(cadenceStore,cadenceRemote);await cadenceEngine.SyncAsync(localChangesOnly:true);var initialManifests=cadenceRemote.ManifestCount;
 using(var fence=await cadenceEngine.AcquireCollaborationAsync("cadence")){for(var n=0;n<4;n++){cadenceStore.UpdateMarkdown(cadenceFile.Path,TextPackStore.Markdown(cadenceStore.Read(cadenceFile.Path))+" typed",cadenceStore.Describe(cadenceFile.Path).Hash);await cadenceEngine.SyncAsync(localChangesOnly:true);}Assert(cadenceRemote.ManifestCount==initialManifests,"protected typing wakeups make no cloud manifest requests");await cadenceEngine.SyncAsync();Assert(cadenceRemote.ManifestCount==initialManifests+1,"scheduled full pass still discovers remote changes during typing");}
 await cadenceEngine.SyncAsync(localChangesOnly:true);Assert(cadenceRemote.UploadCount==2&&cadenceRemote.ManifestCount==initialManifests+2,"unprotected dirty file still synchronizes on local wake");var afterDirty=cadenceRemote.ManifestCount;await cadenceEngine.SyncAsync(localChangesOnly:true);Assert(cadenceRemote.ManifestCount==afterDirty,"unchanged local wake does not poll cloud");
 cadenceStore.Rename(cadenceFile.Path,"Notes/CadenceRenamed.textpack",cadenceStore.Describe(cadenceFile.Path).Hash);await cadenceEngine.SyncAsync(localChangesOnly:true);Assert(cadenceRemote.Item!.RelativePath=="Notes/CadenceRenamed.textpack","local wake still uploads explicit rename");cadenceStore.Delete("Notes/CadenceRenamed.textpack",cadenceStore.Describe("Notes/CadenceRenamed.textpack").Hash);await cadenceEngine.SyncAsync(localChangesOnly:true);Assert(cadenceRemote.DeleteCount==1,"local wake still uploads explicit delete");
 await ReadinessTests.Run(temp);
 PackLayoutTests.Run(temp);
 await TransportTests.Run();
 Console.WriteLine("All native file and durable sync regression tests passed.");
 }finally{Directory.Delete(temp,true);}}
 sealed class Many:ISyncTransport {
  public Dictionary<string,Fake> Items=[];
  Fake Get(string id){if(!Items.TryGetValue(id,out var value))Items[id]=value=new();return value;}
  public Task<IReadOnlyList<RemoteItem>> ManifestAsync(CancellationToken cancellation=default)=>Task.FromResult<IReadOnlyList<RemoteItem>>(Items.Values.Where(x=>x.Item!=null).Select(x=>x.Item!).ToArray());
  public Task<RemotePack> DownloadAsync(string itemId,CancellationToken cancellation=default)=>Get(itemId).DownloadAsync(itemId,cancellation);
  public Task<string> UploadAsync(string itemId,string path,byte[] data,string? baseRevision,string operationId,CancellationToken cancellation=default)=>Get(itemId).UploadAsync(itemId,path,data,baseRevision,operationId,cancellation);
  public Task<string> RenameAsync(string itemId,string from,string to,string baseRevision,string operationId,CancellationToken cancellation=default)=>Get(itemId).RenameAsync(itemId,from,to,baseRevision,operationId,cancellation);
  public Task DeleteAsync(string itemId,string path,string baseRevision,string operationId,CancellationToken cancellation=default)=>Get(itemId).DeleteAsync(itemId,path,baseRevision,operationId,cancellation);
 }
 sealed class Fake:ISyncTransport{
  public System.Net.HttpStatusCode? DownloadFailure;public RemoteItem? Item;public byte[] Data=[];public int UploadCount,DeleteCount,ManifestCount;public bool FailAfterCommit;public List<string> Operations=[];readonly Dictionary<string,string> receipts=[];
  public Task<IReadOnlyList<RemoteItem>> ManifestAsync(CancellationToken cancellation=default){ManifestCount++;return Task.FromResult<IReadOnlyList<RemoteItem>>(Item==null?[]:[Item]);}
  public Task<RemotePack> DownloadAsync(string itemId,CancellationToken cancellation=default){if(DownloadFailure!=null)throw new HttpRequestException("Remote item unavailable.",null,DownloadFailure);return Task.FromResult(new RemotePack(Data,Item!.RelativePath,Item.Revision));}
  public Task<string> UploadAsync(string itemId,string path,byte[] data,string? baseRevision,string operationId,CancellationToken cancellation=default){Operations.Add(operationId);if(receipts.TryGetValue(operationId,out var old))return Task.FromResult(old);if(Item!=null&&Item.Revision!=baseRevision)throw new SyncConflictException();Data=data;var revision=TextPackStore.Hash(data);Item=new(itemId,path,revision);receipts[operationId]=revision;UploadCount++;if(FailAfterCommit){FailAfterCommit=false;throw new HttpRequestException("ACK lost");}return Task.FromResult(revision);}
  public Task<string> RenameAsync(string itemId,string from,string to,string baseRevision,string operationId,CancellationToken cancellation=default){Item=Item! with{RelativePath=to};return Task.FromResult(Item.Revision);}
  public Task DeleteAsync(string itemId,string path,string baseRevision,string operationId,CancellationToken cancellation=default){Item=Item! with{Deleted=true};DeleteCount++;return Task.CompletedTask;}
 }
}
