// Generated by scripts/generate-builtin-presets.ts from presets/builtin/*.textpack.
// Edit the TextPacks, then run npm run presets:generate.
import Foundation

enum GeneratedBuiltinTemplates {
    static let json = #"""
[
  {
    "schemaVersion": 1,
    "engineVersion": 1,
    "id": "texttext.article",
    "version": 1,
    "name": "Blog post",
    "description": "A clear story with a title, byline, cover, and one reading column.",
    "fields": [
      {
        "id": "cover",
        "label": "Cover",
        "required": false,
        "visibility": "public",
        "type": "image",
        "allowedContentTypes": []
      }
    ],
    "item": {
      "type": "stack",
      "direction": "vertical",
      "gap": "lg",
      "align": "stretch",
      "children": [
        {
          "type": "masthead",
          "gap": "sm",
          "children": [
            {
              "type": "text",
              "bind": "content.title",
              "role": "title",
              "fallback": "Untitled"
            },
            {
              "showWhen": "content.subtitle",
              "type": "text",
              "bind": "content.subtitle",
              "role": "subtitle"
            },
            {
              "type": "byline"
            }
          ]
        },
        {
          "type": "cover",
          "bind": "content.fields.cover",
          "alt": "content.title",
          "fit": "cover",
          "height": "large"
        },
        {
          "type": "prose",
          "bind": "content.body"
        }
      ]
    },
    "collection": {
      "layout": "cards",
      "columns": 3,
      "gap": "md",
      "sort": [
        {
          "field": "updatedAt",
          "direction": "desc"
        }
      ],
      "filters": [],
      "views": [],
      "item": {
        "type": "stack",
        "direction": "vertical",
        "gap": "sm",
        "align": "stretch",
        "children": [
          {
            "type": "cover",
            "bind": "content.fields.cover",
            "alt": "content.title",
            "fit": "cover",
            "height": "compact"
          },
          {
            "type": "text",
            "bind": "content.title",
            "role": "heading",
            "fallback": "Untitled"
          },
          {
            "showWhen": "content.subtitle",
            "type": "text",
            "bind": "content.subtitle",
            "role": "caption"
          }
        ]
      }
    },
    "theme": {
      "typography": "editorial",
      "measure": "reading",
      "alignment": "center",
      "media": "contained"
    }
  },
  {
    "schemaVersion": 1,
    "engineVersion": 1,
    "id": "texttext.note",
    "version": 1,
    "name": "Note",
    "description": "A quick private note with no ceremony.",
    "fields": [],
    "item": {
      "type": "stack",
      "direction": "vertical",
      "gap": "sm",
      "align": "stretch",
      "children": [
        {
          "type": "text",
          "bind": "content.title",
          "role": "title",
          "fallback": "Untitled"
        },
        {
          "showWhen": "content.subtitle",
          "type": "text",
          "bind": "content.subtitle",
          "role": "subtitle"
        },
        {
          "type": "prose",
          "bind": "content.body"
        }
      ]
    },
    "collection": {
      "layout": "list",
      "columns": 1,
      "gap": "sm",
      "sort": [
        {
          "field": "updatedAt",
          "direction": "desc"
        }
      ],
      "filters": [],
      "views": [],
      "item": {
        "type": "stack",
        "direction": "vertical",
        "gap": "xs",
        "align": "stretch",
        "children": [
          {
            "type": "text",
            "bind": "content.title",
            "role": "heading",
            "fallback": "Untitled"
          },
          {
            "type": "prose",
            "bind": "content.body"
          }
        ]
      }
    },
    "theme": {
      "typography": "system",
      "measure": "reading",
      "alignment": "start"
    }
  },
  {
    "schemaVersion": 1,
    "engineVersion": 1,
    "id": "texttext.bookmark",
    "version": 1,
    "name": "Bookmark",
    "description": "A calm reading view of a page you saved.",
    "fields": [
      {
        "id": "cover",
        "label": "Cover",
        "required": false,
        "visibility": "public",
        "type": "image",
        "allowedContentTypes": []
      },
      {
        "id": "sourceUrl",
        "label": "Original link",
        "required": true,
        "visibility": "public",
        "type": "url"
      }
    ],
    "item": {
      "type": "stack",
      "direction": "vertical",
      "gap": "lg",
      "align": "stretch",
      "children": [
        {
          "type": "masthead",
          "gap": "sm",
          "children": [
            {
              "type": "text",
              "bind": "content.title",
              "role": "title",
              "fallback": "Untitled"
            },
            {
              "showWhen": "content.subtitle",
              "type": "text",
              "bind": "content.subtitle",
              "role": "subtitle"
            },
            {
              "showWhen": "content.fields.sourceUrl",
              "type": "text",
              "bind": "content.fields.sourceUrl",
              "role": "caption",
              "href": "content.fields.sourceUrl"
            },
            {
              "type": "metadata"
            }
          ]
        },
        {
          "showWhen": "content.fields.cover",
          "type": "cover",
          "bind": "content.fields.cover",
          "alt": "content.title",
          "fit": "cover",
          "height": "medium"
        },
        {
          "type": "prose",
          "bind": "content.body"
        }
      ]
    },
    "collection": {
      "layout": "cards",
      "columns": 3,
      "gap": "md",
      "sort": [
        {
          "field": "updatedAt",
          "direction": "desc"
        }
      ],
      "filters": [],
      "views": [],
      "item": {
        "type": "stack",
        "direction": "vertical",
        "gap": "sm",
        "align": "stretch",
        "children": [
          {
            "type": "cover",
            "bind": "content.fields.cover",
            "alt": "content.title",
            "fit": "cover",
            "height": "compact"
          },
          {
            "type": "text",
            "bind": "content.title",
            "role": "heading",
            "fallback": "Untitled"
          },
          {
            "showWhen": "content.subtitle",
            "type": "text",
            "bind": "content.subtitle",
            "role": "caption"
          }
        ]
      }
    },
    "theme": {
      "typography": "editorial",
      "measure": "reading",
      "alignment": "start",
      "media": "contained"
    }
  },
  {
    "schemaVersion": 1,
    "engineVersion": 1,
    "id": "texttext.gallery",
    "version": 1,
    "name": "Gallery",
    "description": "A set of photos that leads with the images.",
    "fields": [
      {
        "id": "cover",
        "label": "Cover",
        "required": false,
        "visibility": "public",
        "type": "image",
        "allowedContentTypes": []
      }
    ],
    "item": {
      "type": "stack",
      "direction": "vertical",
      "gap": "lg",
      "align": "stretch",
      "children": [
        {
          "id": "gallery-media",
          "type": "gallery",
          "bind": "content.assets",
          "columns": 4,
          "showCaptions": false
        }
      ]
    },
    "collection": {
      "layout": "cards",
      "columns": 4,
      "gap": "md",
      "sort": [
        {
          "field": "updatedAt",
          "direction": "desc"
        }
      ],
      "filters": [],
      "views": [],
      "item": {
        "type": "gallery",
        "bind": "content.assets",
        "columns": 1,
        "showCaptions": false
      }
    },
    "theme": {
      "typography": "system",
      "measure": "full",
      "alignment": "start",
      "media": "full"
    }
  },
  {
    "schemaVersion": 1,
    "engineVersion": 1,
    "id": "texttext.talk",
    "version": 1,
    "name": "Presentation",
    "description": "A talk with a cover, recording, and speaker notes.",
    "fields": [
      {
        "id": "cover",
        "label": "Cover",
        "required": false,
        "visibility": "public",
        "type": "image",
        "allowedContentTypes": []
      },
      {
        "id": "videoUrl",
        "label": "Video",
        "required": false,
        "visibility": "public",
        "type": "url"
      }
    ],
    "item": {
      "type": "stack",
      "direction": "vertical",
      "gap": "lg",
      "align": "stretch",
      "children": [
        {
          "type": "masthead",
          "gap": "sm",
          "children": [
            {
              "type": "text",
              "bind": "content.title",
              "role": "title",
              "fallback": "Untitled"
            },
            {
              "type": "byline"
            },
            {
              "showWhen": "content.subtitle",
              "type": "text",
              "bind": "content.subtitle",
              "role": "subtitle"
            }
          ]
        },
        {
          "showWhen": "content.fields.cover",
          "type": "cover",
          "bind": "content.fields.cover",
          "alt": "content.title",
          "fit": "cover",
          "height": "large"
        },
        {
          "showWhen": "content.fields.videoUrl",
          "type": "video",
          "bind": "content.fields.videoUrl",
          "alt": "content.title",
          "fit": "cover",
          "height": "large"
        },
        {
          "type": "prose",
          "bind": "content.body"
        }
      ]
    },
    "collection": {
      "layout": "cards",
      "columns": 3,
      "gap": "md",
      "sort": [
        {
          "field": "updatedAt",
          "direction": "desc"
        }
      ],
      "filters": [],
      "views": [],
      "item": {
        "type": "stack",
        "direction": "vertical",
        "gap": "sm",
        "align": "stretch",
        "children": [
          {
            "type": "cover",
            "bind": "content.fields.cover",
            "alt": "content.title",
            "fit": "cover",
            "height": "compact"
          },
          {
            "type": "text",
            "bind": "content.title",
            "role": "heading",
            "fallback": "Untitled"
          },
          {
            "showWhen": "content.subtitle",
            "type": "text",
            "bind": "content.subtitle",
            "role": "caption"
          }
        ]
      }
    },
    "theme": {
      "typography": "system",
      "measure": "wide",
      "alignment": "start",
      "media": "contained"
    }
  },
  {
    "schemaVersion": 1,
    "engineVersion": 1,
    "id": "texttext.timeline",
    "version": 1,
    "name": "Timeline",
    "description": "Articles as a dated run, newest first, with the date and reading time under each title.",
    "fields": [
      {
        "id": "cover",
        "label": "Cover",
        "required": false,
        "visibility": "public",
        "type": "image",
        "allowedContentTypes": []
      }
    ],
    "item": {
      "type": "stack",
      "direction": "vertical",
      "gap": "lg",
      "align": "stretch",
      "children": [
        {
          "type": "masthead",
          "gap": "sm",
          "children": [
            {
              "type": "text",
              "bind": "content.title",
              "role": "title",
              "fallback": "Untitled"
            },
            {
              "showWhen": "content.subtitle",
              "type": "text",
              "bind": "content.subtitle",
              "role": "subtitle"
            },
            {
              "type": "byline"
            }
          ]
        },
        {
          "type": "cover",
          "bind": "content.fields.cover",
          "alt": "content.title",
          "fit": "cover",
          "height": "large"
        },
        {
          "type": "prose",
          "bind": "content.body"
        }
      ]
    },
    "collection": {
      "layout": "timeline",
      "columns": 1,
      "gap": "md",
      "sort": [
        {
          "field": "updatedAt",
          "direction": "desc"
        }
      ],
      "filters": [],
      "views": [],
      "item": {
        "type": "stack",
        "direction": "vertical",
        "gap": "sm",
        "align": "stretch",
        "children": [
          {
            "type": "cover",
            "bind": "content.fields.cover",
            "alt": "content.title",
            "fit": "cover",
            "height": "compact"
          },
          {
            "type": "text",
            "bind": "content.title",
            "role": "heading",
            "fallback": "Untitled"
          },
          {
            "showWhen": "content.subtitle",
            "type": "text",
            "bind": "content.subtitle",
            "role": "caption"
          }
        ]
      }
    },
    "theme": {
      "typography": "editorial",
      "measure": "reading",
      "alignment": "center",
      "media": "contained"
    }
  },
  {
    "schemaVersion": 1,
    "engineVersion": 1,
    "id": "texttext.casestudy",
    "version": 1,
    "name": "Case study",
    "description": "The work on the left, the proof of it on the right.",
    "fields": [
      {
        "id": "cover",
        "label": "Evidence",
        "required": false,
        "visibility": "public",
        "type": "image",
        "allowedContentTypes": []
      },
      {
        "id": "videoUrl",
        "label": "Video",
        "required": false,
        "visibility": "public",
        "type": "url"
      },
      {
        "id": "caption",
        "label": "Caption",
        "required": false,
        "visibility": "public",
        "type": "text"
      },
      {
        "id": "role",
        "label": "Role",
        "required": false,
        "visibility": "public",
        "type": "text"
      }
    ],
    "item": {
      "type": "stack",
      "direction": "horizontal",
      "gap": "xl",
      "align": "start",
      "children": [
        {
          "id": "case-copy",
          "type": "stack",
          "direction": "vertical",
          "gap": "md",
          "align": "stretch",
          "children": [
            {
              "type": "masthead",
              "gap": "sm",
              "children": [
                {
                  "type": "text",
                  "bind": "content.title",
                  "role": "title",
                  "fallback": "Untitled"
                },
                {
                  "type": "badge",
                  "bind": "content.tags",
                  "variant": "pill",
                  "showIcon": true
                },
                {
                  "showWhen": "content.fields.role",
                  "type": "text",
                  "bind": "content.fields.role",
                  "role": "caption"
                }
              ]
            },
            {
              "type": "prose",
              "bind": "content.body"
            }
          ]
        },
        {
          "id": "case-evidence",
          "type": "stack",
          "direction": "vertical",
          "gap": "sm",
          "align": "stretch",
          "children": [
            {
              "showWhen": "content.fields.videoUrl",
              "type": "video",
              "bind": "content.fields.videoUrl",
              "alt": "content.title",
              "fit": "cover",
              "height": "medium"
            },
            {
              "showWhen": "content.fields.cover",
              "type": "cover",
              "bind": "content.fields.cover",
              "alt": "content.title",
              "fit": "cover",
              "height": "medium"
            },
            {
              "showWhen": "content.fields.caption",
              "type": "text",
              "bind": "content.fields.caption",
              "role": "caption"
            }
          ]
        }
      ]
    },
    "collection": {
      "layout": "cards",
      "columns": 2,
      "gap": "md",
      "sort": [
        {
          "field": "updatedAt",
          "direction": "desc"
        }
      ],
      "filters": [],
      "views": [],
      "item": {
        "type": "stack",
        "direction": "vertical",
        "gap": "xs",
        "align": "stretch",
        "children": [
          {
            "showWhen": "content.fields.cover",
            "type": "cover",
            "bind": "content.fields.cover",
            "alt": "content.title",
            "fit": "cover",
            "height": "compact"
          },
          {
            "type": "text",
            "bind": "content.title",
            "role": "heading",
            "fallback": "Untitled"
          },
          {
            "showWhen": "content.fields.role",
            "type": "text",
            "bind": "content.fields.role",
            "role": "caption"
          }
        ]
      }
    },
    "theme": {
      "typography": "system",
      "measure": "full",
      "alignment": "start",
      "media": "contained"
    }
  },
  {
    "schemaVersion": 1,
    "engineVersion": 1,
    "id": "texttext.page",
    "version": 1,
    "name": "Page",
    "description": "A plain page: a cover, an icon, and what you write.",
    "fields": [
      {
        "id": "cover",
        "label": "Cover",
        "required": false,
        "visibility": "public",
        "type": "image",
        "allowedContentTypes": []
      },
      {
        "id": "icon",
        "label": "Icon",
        "required": false,
        "visibility": "public",
        "help": "One emoji.",
        "type": "text"
      }
    ],
    "item": {
      "type": "stack",
      "direction": "vertical",
      "gap": "none",
      "align": "stretch",
      "children": [
        {
          "showWhen": "content.fields.cover",
          "type": "cover",
          "bind": "content.fields.cover",
          "alt": "content.title",
          "fit": "cover",
          "height": "compact"
        },
        {
          "id": "page-icon",
          "showWhen": "content.fields.icon",
          "type": "text",
          "bind": "content.fields.icon",
          "role": "heading"
        },
        {
          "type": "masthead",
          "gap": "xs",
          "children": [
            {
              "type": "text",
              "bind": "content.title",
              "role": "title",
              "fallback": "Untitled"
            },
            {
              "showWhen": "content.subtitle",
              "type": "text",
              "bind": "content.subtitle",
              "role": "subtitle"
            }
          ]
        },
        {
          "type": "prose",
          "bind": "content.body"
        }
      ]
    },
    "collection": {
      "layout": "list",
      "columns": 1,
      "gap": "sm",
      "sort": [
        {
          "field": "updatedAt",
          "direction": "desc"
        }
      ],
      "filters": [],
      "views": [],
      "item": {
        "type": "stack",
        "direction": "vertical",
        "gap": "xs",
        "align": "stretch",
        "children": [
          {
            "type": "text",
            "bind": "content.title",
            "role": "heading",
            "fallback": "Untitled"
          },
          {
            "showWhen": "content.subtitle",
            "type": "text",
            "bind": "content.subtitle",
            "role": "caption"
          }
        ]
      }
    },
    "theme": {
      "typography": "system",
      "measure": "reading",
      "alignment": "start",
      "media": "bleed"
    }
  },
  {
    "schemaVersion": 1,
    "engineVersion": 1,
    "id": "texttext.todo",
    "version": 1,
    "name": "Task list",
    "description": "A simple checklist in one file.",
    "fields": [
      {
        "id": "items",
        "label": "Tasks",
        "required": false,
        "visibility": "public",
        "type": "rows",
        "fields": [
          {
            "id": "task",
            "label": "Task",
            "required": true,
            "visibility": "public",
            "type": "text"
          },
          {
            "id": "done",
            "label": "Done",
            "required": false,
            "visibility": "public",
            "type": "boolean"
          }
        ],
        "maxRows": 200
      }
    ],
    "item": {
      "type": "stack",
      "direction": "vertical",
      "gap": "md",
      "align": "stretch",
      "children": [
        {
          "type": "text",
          "bind": "content.title",
          "role": "title",
          "fallback": "Untitled list"
        },
        {
          "type": "checklist",
          "bind": "content.fields.items",
          "doneBind": "row.done",
          "labelBind": "row.task",
          "meta": [],
          "mode": "document",
          "sortCheckedLast": false,
          "rollup": false
        }
      ]
    },
    "collection": {
      "layout": "list",
      "columns": 1,
      "gap": "sm",
      "sort": [
        {
          "field": "updatedAt",
          "direction": "desc"
        }
      ],
      "filters": [],
      "views": [],
      "item": {
        "type": "stack",
        "direction": "vertical",
        "gap": "xs",
        "align": "stretch",
        "children": [
          {
            "type": "text",
            "bind": "content.title",
            "role": "heading",
            "fallback": "Untitled list"
          },
          {
            "showWhen": "content.fields.items",
            "type": "progress",
            "variant": "fraction",
            "source": {
              "checklistBind": "content.fields.items",
              "doneBind": "row.done"
            }
          }
        ]
      }
    },
    "theme": {
      "typography": "system",
      "density": "compact",
      "measure": "reading",
      "alignment": "start"
    }
  },
  {
    "schemaVersion": 1,
    "engineVersion": 1,
    "id": "texttext.project",
    "version": 1,
    "name": "Project",
    "description": "A project page with status, dates, and tasks.",
    "fields": [
      {
        "id": "status",
        "label": "Status",
        "required": false,
        "visibility": "public",
        "type": "enum",
        "options": [
          {
            "value": "planned",
            "label": "Planned",
            "tone": "neutral",
            "icon": "🗓️"
          },
          {
            "value": "active",
            "label": "Active",
            "tone": "info",
            "icon": "🔵"
          },
          {
            "value": "blocked",
            "label": "Blocked",
            "tone": "danger",
            "icon": "⛔"
          },
          {
            "value": "done",
            "label": "Done",
            "tone": "success",
            "icon": "✅"
          }
        ],
        "multiple": false
      },
      {
        "id": "lead",
        "label": "Lead",
        "required": false,
        "visibility": "public",
        "type": "text"
      },
      {
        "id": "due",
        "label": "Due",
        "required": false,
        "visibility": "public",
        "type": "date"
      },
      {
        "id": "milestones",
        "label": "Milestones",
        "required": false,
        "visibility": "public",
        "type": "rows",
        "fields": [
          {
            "id": "milestone",
            "label": "Milestone",
            "required": true,
            "visibility": "public",
            "type": "text"
          },
          {
            "id": "due",
            "label": "Due",
            "required": false,
            "visibility": "public",
            "type": "date"
          },
          {
            "id": "reached",
            "label": "Reached",
            "required": false,
            "visibility": "public",
            "type": "boolean"
          }
        ],
        "maxRows": 200
      },
      {
        "id": "tasks",
        "label": "Tasks",
        "required": false,
        "visibility": "public",
        "type": "rows",
        "fields": [
          {
            "id": "task",
            "label": "Task",
            "required": true,
            "visibility": "public",
            "type": "text"
          },
          {
            "id": "done",
            "label": "Done",
            "required": false,
            "visibility": "public",
            "type": "boolean"
          },
          {
            "id": "owner",
            "label": "Owner",
            "required": false,
            "visibility": "public",
            "type": "text"
          },
          {
            "id": "due",
            "label": "Due",
            "required": false,
            "visibility": "public",
            "type": "date"
          }
        ],
        "maxRows": 200
      },
      {
        "id": "risks",
        "label": "Risks",
        "required": false,
        "visibility": "public",
        "type": "richtext"
      }
    ],
    "item": {
      "type": "stack",
      "direction": "vertical",
      "gap": "md",
      "align": "stretch",
      "children": [
        {
          "type": "masthead",
          "gap": "sm",
          "children": [
            {
              "type": "text",
              "bind": "content.title",
              "role": "title",
              "fallback": "Untitled project"
            },
            {
              "showWhen": "content.subtitle",
              "type": "text",
              "bind": "content.subtitle",
              "role": "subtitle"
            },
            {
              "type": "facts",
              "variant": "table",
              "entries": [
                {
                  "bind": "content.fields.status",
                  "label": "Status"
                },
                {
                  "bind": "content.fields.lead",
                  "label": "Lead"
                },
                {
                  "bind": "content.fields.due",
                  "label": "Due",
                  "format": "countdown"
                }
              ]
            }
          ]
        },
        {
          "showWhen": "content.body",
          "type": "prose",
          "bind": "content.body"
        },
        {
          "showWhen": "content.fields.tasks",
          "type": "progress",
          "variant": "bar",
          "source": {
            "checklistBind": "content.fields.tasks",
            "doneBind": "row.done"
          }
        },
        {
          "showWhen": "content.fields.milestones",
          "type": "rows",
          "bind": "content.fields.milestones",
          "variant": "timeline",
          "columns": [
            {
              "bind": "row.milestone",
              "label": "Milestone"
            },
            {
              "bind": "row.due",
              "label": "Due"
            },
            {
              "bind": "row.reached",
              "label": "Reached"
            }
          ],
          "sort": {
            "bind": "row.due",
            "direction": "asc"
          }
        },
        {
          "showWhen": "content.fields.tasks",
          "type": "checklist",
          "bind": "content.fields.tasks",
          "doneBind": "row.done",
          "labelBind": "row.task",
          "meta": [
            "row.owner",
            "row.due"
          ],
          "mode": "document",
          "sortCheckedLast": true,
          "rollup": true
        },
        {
          "showWhen": "content.fields.risks",
          "type": "callout",
          "tone": "warning",
          "title": "Risks",
          "children": [
            {
              "type": "prose",
              "bind": "content.fields.risks"
            }
          ]
        }
      ]
    },
    "collection": {
      "layout": "board",
      "columns": 1,
      "gap": "sm",
      "groupBy": "content.fields.status",
      "sort": [
        {
          "field": "content.fields.due",
          "direction": "asc"
        }
      ],
      "filters": [],
      "views": [],
      "item": {
        "type": "stack",
        "direction": "vertical",
        "gap": "xs",
        "align": "stretch",
        "children": [
          {
            "type": "text",
            "bind": "content.title",
            "role": "heading",
            "fallback": "Untitled project"
          },
          {
            "showWhen": "content.fields.status",
            "type": "badge",
            "bind": "content.fields.status",
            "variant": "pill",
            "showIcon": true
          },
          {
            "type": "facts",
            "variant": "strip",
            "entries": [
              {
                "bind": "content.fields.due",
                "label": "Due",
                "format": "countdown"
              }
            ]
          },
          {
            "showWhen": "content.fields.tasks",
            "type": "progress",
            "variant": "fraction",
            "source": {
              "checklistBind": "content.fields.tasks",
              "doneBind": "row.done"
            }
          }
        ]
      }
    },
    "theme": {
      "typography": "system",
      "density": "compact",
      "measure": "wide",
      "alignment": "start"
    }
  },
  {
    "schemaVersion": 1,
    "engineVersion": 1,
    "id": "texttext.brief",
    "version": 1,
    "name": "Living brief",
    "description": "A grounded brief with visible sources, claims, and writing rules.",
    "fields": [
      {
        "id": "audience",
        "label": "Audience",
        "required": false,
        "visibility": "public",
        "type": "text"
      },
      {
        "id": "purpose",
        "label": "Purpose",
        "required": false,
        "visibility": "public",
        "type": "enum",
        "options": [
          {
            "value": "decision",
            "label": "Decision",
            "tone": "info"
          },
          {
            "value": "alignment",
            "label": "Alignment",
            "tone": "neutral"
          },
          {
            "value": "publication",
            "label": "Publication",
            "tone": "success"
          },
          {
            "value": "research",
            "label": "Research",
            "tone": "accent"
          }
        ],
        "multiple": false
      },
      {
        "id": "lastReviewed",
        "label": "Last reviewed",
        "required": false,
        "visibility": "public",
        "type": "date"
      },
      {
        "id": "sources",
        "label": "Sources",
        "required": false,
        "visibility": "public",
        "type": "rows",
        "fields": [
          {
            "id": "sourceId",
            "label": "Source id",
            "required": true,
            "visibility": "hidden",
            "type": "text"
          },
          {
            "id": "itemId",
            "label": "Workspace item",
            "required": false,
            "visibility": "hidden",
            "type": "reference",
            "target": "document",
            "multiple": false
          },
          {
            "id": "title",
            "label": "Source",
            "required": true,
            "visibility": "public",
            "type": "text"
          },
          {
            "id": "kind",
            "label": "Kind",
            "required": false,
            "visibility": "editor",
            "type": "enum",
            "options": [
              {
                "value": "workspace",
                "label": "Workspace",
                "tone": "info"
              },
              {
                "value": "web",
                "label": "Web",
                "tone": "neutral"
              }
            ],
            "multiple": false
          },
          {
            "id": "url",
            "label": "Link",
            "required": false,
            "visibility": "public",
            "type": "url"
          },
          {
            "id": "capturedHash",
            "label": "Captured version",
            "required": false,
            "visibility": "hidden",
            "type": "text"
          },
          {
            "id": "status",
            "label": "Status",
            "required": false,
            "visibility": "public",
            "type": "enum",
            "options": [
              {
                "value": "current",
                "label": "Current",
                "tone": "success"
              },
              {
                "value": "changed",
                "label": "Changed",
                "tone": "warning"
              },
              {
                "value": "missing",
                "label": "Missing",
                "tone": "danger"
              },
              {
                "value": "unverified",
                "label": "Unverified",
                "tone": "neutral"
              }
            ],
            "multiple": false
          },
          {
            "id": "note",
            "label": "Used for",
            "required": false,
            "visibility": "public",
            "type": "text"
          }
        ],
        "maxRows": 200
      },
      {
        "id": "claims",
        "label": "Claims",
        "required": false,
        "visibility": "public",
        "type": "rows",
        "fields": [
          {
            "id": "claimId",
            "label": "Claim id",
            "required": true,
            "visibility": "hidden",
            "type": "text"
          },
          {
            "id": "claim",
            "label": "Claim",
            "required": true,
            "visibility": "public",
            "type": "text"
          },
          {
            "id": "sourceId",
            "label": "Source",
            "required": true,
            "visibility": "public",
            "type": "text"
          },
          {
            "id": "evidence",
            "label": "Evidence",
            "required": false,
            "visibility": "public",
            "type": "text"
          },
          {
            "id": "status",
            "label": "Status",
            "required": false,
            "visibility": "public",
            "type": "enum",
            "options": [
              {
                "value": "supported",
                "label": "Supported",
                "tone": "success"
              },
              {
                "value": "review",
                "label": "Review",
                "tone": "warning"
              },
              {
                "value": "unsupported",
                "label": "Unsupported",
                "tone": "danger"
              }
            ],
            "multiple": false
          }
        ],
        "maxRows": 300
      },
      {
        "id": "writingRules",
        "label": "Writing rules",
        "required": false,
        "visibility": "public",
        "type": "rows",
        "fields": [
          {
            "id": "instruction",
            "label": "Rule",
            "required": true,
            "visibility": "public",
            "type": "text"
          },
          {
            "id": "scope",
            "label": "Scope",
            "required": false,
            "visibility": "public",
            "type": "enum",
            "options": [
              {
                "value": "document",
                "label": "Document",
                "tone": "neutral"
              },
              {
                "value": "selection",
                "label": "Selection",
                "tone": "info"
              },
              {
                "value": "publication",
                "label": "Publication",
                "tone": "success"
              }
            ],
            "multiple": false
          },
          {
            "id": "enabled",
            "label": "Enabled",
            "required": false,
            "visibility": "public",
            "type": "boolean"
          }
        ],
        "maxRows": 100
      },
      {
        "id": "claimsHeading",
        "label": "Claims heading",
        "required": false,
        "visibility": "hidden",
        "type": "text"
      },
      {
        "id": "sourcesHeading",
        "label": "Sources heading",
        "required": false,
        "visibility": "hidden",
        "type": "text"
      },
      {
        "id": "rulesHeading",
        "label": "Writing rules heading",
        "required": false,
        "visibility": "hidden",
        "type": "text"
      }
    ],
    "item": {
      "type": "stack",
      "direction": "vertical",
      "gap": "lg",
      "align": "stretch",
      "children": [
        {
          "type": "masthead",
          "gap": "sm",
          "children": [
            {
              "type": "text",
              "bind": "content.title",
              "role": "title",
              "fallback": "Untitled brief"
            },
            {
              "showWhen": "content.subtitle",
              "type": "text",
              "bind": "content.subtitle",
              "role": "subtitle"
            },
            {
              "type": "facts",
              "variant": "strip",
              "entries": [
                {
                  "bind": "content.fields.audience",
                  "label": "Audience"
                },
                {
                  "bind": "content.fields.purpose",
                  "label": "Purpose"
                },
                {
                  "bind": "content.fields.lastReviewed",
                  "label": "Reviewed",
                  "format": "date"
                }
              ]
            }
          ]
        },
        {
          "showWhen": "content.body",
          "type": "prose",
          "bind": "content.body"
        },
        {
          "id": "claims-heading",
          "showWhen": "content.fields.claims",
          "type": "text",
          "bind": "content.fields.claimsHeading",
          "role": "heading",
          "fallback": "Claims"
        },
        {
          "id": "claims-ledger",
          "showWhen": "content.fields.claims",
          "type": "rows",
          "bind": "content.fields.claims",
          "variant": "table",
          "columns": [
            {
              "bind": "row.claimId",
              "label": "ID"
            },
            {
              "bind": "row.claim",
              "label": "Claim"
            },
            {
              "bind": "row.status",
              "label": "Status"
            },
            {
              "bind": "row.sourceId",
              "label": "Source"
            },
            {
              "bind": "row.evidence",
              "label": "Evidence"
            }
          ]
        },
        {
          "id": "sources-heading",
          "showWhen": "content.fields.sources",
          "type": "text",
          "bind": "content.fields.sourcesHeading",
          "role": "heading",
          "fallback": "Sources"
        },
        {
          "id": "sources-ledger",
          "showWhen": "content.fields.sources",
          "type": "rows",
          "bind": "content.fields.sources",
          "variant": "table",
          "columns": [
            {
              "bind": "row.sourceId",
              "label": "ID"
            },
            {
              "bind": "row.title",
              "label": "Source"
            },
            {
              "bind": "row.status",
              "label": "Status"
            },
            {
              "bind": "row.url",
              "label": "Link"
            },
            {
              "bind": "row.note",
              "label": "Used for"
            }
          ]
        },
        {
          "id": "rules-heading",
          "showWhen": "content.fields.writingRules",
          "type": "text",
          "bind": "content.fields.rulesHeading",
          "role": "heading",
          "fallback": "Writing rules"
        },
        {
          "id": "writing-rules",
          "showWhen": "content.fields.writingRules",
          "type": "checklist",
          "bind": "content.fields.writingRules",
          "doneBind": "row.enabled",
          "labelBind": "row.instruction",
          "meta": [
            "row.scope"
          ],
          "mode": "document",
          "sortCheckedLast": false,
          "rollup": false
        }
      ]
    },
    "collection": {
      "layout": "list",
      "columns": 1,
      "gap": "sm",
      "sort": [
        {
          "field": "updatedAt",
          "direction": "desc"
        }
      ],
      "filters": [],
      "views": [],
      "item": {
        "type": "stack",
        "direction": "vertical",
        "gap": "xs",
        "align": "stretch",
        "children": [
          {
            "type": "text",
            "bind": "content.title",
            "role": "heading",
            "fallback": "Untitled brief"
          },
          {
            "type": "facts",
            "variant": "strip",
            "entries": [
              {
                "bind": "content.fields.purpose",
                "label": "Purpose"
              },
              {
                "bind": "content.fields.sources",
                "label": "Sources",
                "derive": {
                  "op": "count"
                }
              }
            ]
          }
        ]
      }
    },
    "theme": {
      "accent": "#0A66C2",
      "typography": "system",
      "density": "comfortable",
      "measure": "wide",
      "corners": "subtle",
      "surface": "paper",
      "titleScale": "standard",
      "bodyScale": "standard",
      "alignment": "start"
    }
  }
]
"""#
}
